### ISSUE TITLE
no redirection after successful login

### ISSUE THREAD

**Issue by 78raoul78** [nextauthjs/next-auth#10016]
### Environment

System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M2
    Memory: 489.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.14.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.1.2
  npmPackages:
    next: 14.1.0 => 14.1.0 
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/78raoul78/ui

### Describe the issue

After a successful signIn, I'm not getting redirected to my home page even though the callbackUrl is correctly set.

### How to reproduce

1. Checkout the repository
2. Create an .env file in apps/www and paste inside the content from app/www/.env.example (put your own AUTH_SECRET and the url of your POSTGRES_URL)
3. Go to apps/www and run pnpm install
4. then pnpm run seed
5. then pnpm build
6. then pnpm dev
7. Go to **http://localhost:3001**
8. You should be redirected to the signIn page **http://localhost:3001/signIn?callbackUrl=http%3A%2F%2Flocalhost%3A3001%2F**
9. submit a valid account credentials : raoulcheck@flexup.com / 123456
10. here is the issue : instead of being redirected to **http://localhost:3001**, you're being redirected to **http://localhost:3001/signIn?callbackUrl=http%3A%2F%2Flocalhost%3A3001%2F** , whats the interest of the callbackUrl if I'm not redirected to it 🤔 

### Expected behavior

After a successful login, I'm expecting to be redirected to the initial url (the one before the redirection) which is localhost:3001

**Comment by nauvalyusufaddairy** [comment]
There are a lot of bugs in version 5. It better try to create an auth flow from scratch or rollback to v4.

**Comment by schilffarth** [comment]
> I am not an official maintainer, but I think you have mistaken callback url with redirect url.
> The callback is for auth, you need to do redirect after you are logged in.
> Here's my code:
> ```
> import { signIn } from "next-auth/react";
> import { useRouter } from "next13-progressbar";
> import { toast } from "sonner";
> 
> 
> export default function Login() {
>   const router = useRouter();
>   
> 
>  const onSubmit = async (values: z.infer<typeof formSchema>) => {
>     setIsLoading(true);
>     const { email, password } = values;
>     try {
>       const resp = await signIn("credentials", {
>         email,
>         password,
>         redirect: false,
>       });
>       if (!resp || resp.error) {
>         toast.error(`Login in failed: ${resp?.error}` || "unkonwn error");
>         return;
>       }
>       toast.success("woohoo");
>       const redirect = searchParams.get("redirect");
>       if (redirect) {
>         router.push(redirect);
>       } else {
>         router.push("/home");
>       }
>     } catch (error) {
>       toast.error(`Login in failed: ${error}` || "unkonwn error");
>       return;
>     } finally {
>       setIsLoading(false);
>     }
>   };
> 
> ...
> ```
> I may be wrong. But you can give this a try.

With this could you probably have /had a similar issue to mine:
After successful login, the app's session isn't updated. The session in my root layout.tsx is logging the correct session data in server side rendering, but `useSession` on client side remains undefined.
A manual page refresh will fix this issue, client side useSession gets uptodate session data.

Anyone familiar with this issue? I do not want to perform a whole page refresh upon login / logout. This sucks.

**Comment by bensonz** [comment]
I think first of all you shouldnt use `getSession()` in layout.
And the client side session should be updated, I recently did a twitter login and it works:
```
import { signIn, signOut, useSession } from "next-auth/react";

export default function ConnectAccount() {
  const { data, status } = useSession();
   
 if (status === "authenticated") {
    return (
      <>
        <Button
          className="w-full"
          variant={"outline"}
          onClick={() => signOut()}
        >
         xxx
       </>);
}
else {
   return (
    <Button
      className="w-full"
      variant={"outline"}
      onClick={() => signIn("twitter")}
    >
      <Image src="/icons/X_logo.svg" width={20} height={20} alt="X" />
    </Button>
  );
}
```
and this signIn works perfectly good.
If you could share your code We can probably figure out something.

**Comment by schilffarth** [comment]
> I think first of all you shouldnt use `getSession()` in layout.
> And the client side session should be updated, I recently did a twitter login and it works:
> ```
> import { signIn, signOut, useSession } from "next-auth/react";
> 
> export default function ConnectAccount() {
>   const { data, status } = useSession();
>    
>  if (status === "authenticated") {
>     return (
>       <>
>         <Button
>           className="w-full"
>           variant={"outline"}
>           onClick={() => signOut()}
>         >
>          xxx
>        </>);
> }
> else {
>    return (
>     <Button
>       className="w-full"
>       variant={"outline"}
>       onClick={() => signIn("twitter")}
>     >
>       <Image src="/icons/X_logo.svg" width={20} height={20} alt="X" />
>     </Button>
>   );
> }
> ```
> and this signIn works perfectly good.
> If you could share your code We can probably figure out something.

My session is initialized / fetched in the root layout with `const session = await auth()`, using next auth beta v11 right now.

This session is passed to the SessionProvider.

In i.e. the AppBar / NavBar, where I have a user button or a login button based on session status, I retrieve the session with `useSession()`.

When I log the `session` in my root layout.tsx, it logs correctly the uptodate sssiondata on server side in my ide console.
But a log in the AppBar where I use useSession remains undefined, even if the root layout logs the correct values.

Upon manual page refresh (or window.location.refresh) the session is passed down correctly and my AppBar useSession returns the proper data.

Recently I discovered that the same issue exists for the auth logout. If redirect is set to false, the logout doesn't actually happen on client side and the session isn't updated until manual page refresh.

The whole situation is all about these annoying page refreshes. I do not wanna reload the entire app upon login/logout, i just want the ui to represent the actual session as anyone would expect.

I will share code later when I get home, unless you have any ideas based on this description already?

**Comment by schilffarth** [comment]
I actually finally made it work thanks to another very recent github issue (cannot find it anymore tho lol)

The underlying issue was that `next-auth`'s session provider doesn't update the session passed from auth() in client side, it only happens upon page refresh.

The solution was to build a custom `SessionProvider` that utilizes `getSession()` instead of `auth()` and passing it as a state onto `next-auth's` `SessionProvider`:

```typescript
"use client";

import { Session } from "next-auth";
import {
    SessionProvider as NextSessionProvider,
    getSession
} from "next-auth/react";
import { usePathname } from "next/navigation";
import {
    ReactNode,
    useCallback,
    useEffect,
    useState
} from "react";

// Retrieve user session for the app's session context
export default function SessionProvider({
    children
}: {
    children: ReactNode;
}) {
    const [ session, setSession ] = useState<Session | null>(null);
    const pathName = usePathname();

    const fetchSession = useCallback(async () => {
        try {
            const sessionData = await getSession();
            setSession(sessionData);
        } catch (error) {
            setSession(null);

            if (process.env.NODE_ENV === "development") {
                console.error(error);
            }
        }
    }, []);

    useEffect(() => {
        fetchSession().finally();
    }, [fetchSession, pathName]);

    return (
        <NextSessionProvider session={session}>
            {children}
        </NextSessionProvider>
    );
}
```

Now I can use `useSession()` from `next-auth` just normally and I am returned the up-to-date session data after login. Now, I do not have to reload the entire app upon login / logout!!!

I am very happy as I finally figured this out, it's been plagueing me for almost 2 months by now.

**Comment by 18601673727** [comment]
Well I think by their [documentation](https://authjs.dev/reference/nextjs/react#usesession):
>&nbsp;&nbsp;
>You will likely not need useSession if you are using the [Next.js App Router](https://nextjs.org/blog/next-13-4#nextjs-app-router).
>&nbsp;&nbsp;

So we are not supposed to `useSession` or `getSession` at the first place, but to [router.reload()](https://nextjs.org/docs/app/api-reference/functions/use-router#userouter) after each `signIn()`, to allow our `const session = await auth()` doing its job properly, let alone confuse ourselves even more with `useEffect + Context` approaches..

**Comment by lespons** [comment]
with server action I use

```typescript
'use server';

import { signIn } from '@/lib/auth';
import { AuthError } from 'next-auth';
import { redirect } from 'next/navigation';

export async function authenticate(_: string | undefined, formData: FormData) {
  try {
    await signIn('credentials', formData);
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return 'Invalid credentials.';
        default:
          return 'Something went wrong.';
      }
    }
    throw error;
  } finally {
    redirect('/'); // or your pathname
  }
}

``` 
and client 
```typescript
...
  const [errorMessage, dispatch] = useFormState(authenticate, undefined);

  return (
    <form action={dispatch} className="..">
...
```

**Comment by rhiskey** [comment]
> I actually finally made it work thanks to another very recent github issue (cannot find it anymore tho lol)
> 
> The underlying issue was that `next-auth`'s session provider doesn't update the session passed from auth() in client side, it only happens upon page refresh.
> 
> The solution was to build a custom `SessionProvider` that utilizes `getSession()` instead of `auth()` and passing it as a state onto `next-auth's` `SessionProvider`:
> 
> ```ts
> "use client";
> 
> import { Session } from "next-auth";
> import {
>     SessionProvider as NextSessionProvider,
>     getSession
> } from "next-auth/react";
> import { usePathname } from "next/navigation";
> import {
>     ReactNode,
>     useCallback,
>     useEffect,
>     useState
> } from "react";
> 
> // Retrieve user session for the app's session context
> export default function SessionProvider({
>     children
> }: {
>     children: ReactNode;
> }) {
>     const [ session, setSession ] = useState<Session | null>(null);
>     const pathName = usePathname();
> 
>     const fetchSession = useCallback(async () => {
>         try {
>             const sessionData = await getSession();
>             setSession(sessionData);
>         } catch (error) {
>             setSession(null);
> 
>             if (process.env.NODE_ENV === "development") {
>                 console.error(error);
>             }
>         }
>     }, []);
> 
>     useEffect(() => {
>         fetchSession().finally();
>     }, [fetchSession, pathName]);
> 
>     return (
>         <NextSessionProvider session={session}>
>             {children}
>         </NextSessionProvider>
>     );
> }
> ```
> 
> Now I can use `useSession()` from `next-auth` just normally and I am returned the up-to-date session data after login. Now, I do not have to reload the entire app upon login / logout!!!
> 
> I am very happy as I finally figured this out, it's been plagueing me for almost 2 months by now.

It works, thanks! Saved my life!

**Comment by rhiskey** [comment]
I found solution without modifying SessionProvider. 
You have to properly split codebase to server/client part. According Next 14 App Router guidelines.

I use
```json
    "next-auth": "^5.0.0-beta.19",
    "next": "^14.2.3",
```

You have to _properly_ split codebase to server/client part. According to Next 14 App Router guidelines.

So, guys, I got your back!

Follow these steps:
1. Create `current-session.ts` in lib folder.

`current-session.ts`
```ts
import { auth } from "@/auth";

/**
 * Retrieves the current user from the authentication session.
 *
 * @return {Promise<User | undefined>} The current user if available, otherwise undefined.
 */
export const currentUser = async () => {
  const session = await auth();

  return session?.user;
};
```

This is our server side session user. Use in any component that supposed to work as server component (by default it is). For example **layout.tsx** or **page.tsx**

3. For example, i use `<Navbar/>` in my `layout.tsx`. I have In Navbar user button  `AuthButton` , so to actually update state of this button (load avatar, nickname, email) after sign-in or sign-up without refreshing page simply pass user to client component (in this case `AuthButton`).

`Navbar.tsx`
```ts
import {currentUser } from "@/lib/current-session";

export const Navbar = async () => {
  // Get user from server side in layout (for example navbar)
  const user = await currentUser();

  return (
     <AuthButton user={user} />
  );
};
```

`AuthButton.tsx` 
```ts AuthButton.tsx
interface AuthButtonProps {
  user?: User
}

export const AuthButton = ({
  user,
}: AuthButtonProps) => {
  if (user) {
      return (
        <div>
            <span>{user.image}</span>
            <p>{user.email}</p>
        </div>
      );
  }
  return (
     <p>Not logged in</p>
  );
};
```

Where user is type of default User. You can extend this via database model 
```ts
type User = {
    id: string;
    image: string;
    email: string;
    // etc...
}
```

Hope it helps, please write back if this works for you @weijyun9008 @lespons @78raoul78

**Comment by wzrdx** [comment]
> I actually finally made it work thanks to another very recent github issue (cannot find it anymore tho lol)
> 
> The underlying issue was that `next-auth`'s session provider doesn't update the session passed from auth() in client side, it only happens upon page refresh.
> 
> The solution was to build a custom `SessionProvider` that utilizes `getSession()` instead of `auth()` and passing it as a state onto `next-auth's` `SessionProvider`:
> 
> ```ts
> "use client";
> 
> import { Session } from "next-auth";
> import {
>     SessionProvider as NextSessionProvider,
>     getSession
> } from "next-auth/react";
> import { usePathname } from "next/navigation";
> import {
>     ReactNode,
>     useCallback,
>     useEffect,
>     useState
> } from "react";
> 
> // Retrieve user session for the app's session context
> export default function SessionProvider({
>     children
> }: {
>     children: ReactNode;
> }) {
>     const [ session, setSession ] = useState<Session | null>(null);
>     const pathName = usePathname();
> 
>     const fetchSession = useCallback(async () => {
>         try {
>             const sessionData = await getSession();
>             setSession(sessionData);
>         } catch (error) {
>             setSession(null);
> 
>             if (process.env.NODE_ENV === "development") {
>                 console.error(error);
>             }
>         }
>     }, []);
> 
>     useEffect(() => {
>         fetchSession().finally();
>     }, [fetchSession, pathName]);
> 
>     return (
>         <NextSessionProvider session={session}>
>             {children}
>         </NextSessionProvider>
>     );
> }
> ```
> 
> Now I can use `useSession()` from `next-auth` just normally and I am returned the up-to-date session data after login. Now, I do not have to reload the entire app upon login / logout!!!
> 
> I am very happy as I finally figured this out, it's been plagueing me for almost 2 months by now.

Using this component, the session is not even updated after reloading lol.

This cannot possibly work as it does the exact same thing useSession().

**Comment by wzrdx** [comment]
> I found solution without modifying SessionProvider. You have to properly split codebase to server/client part. According Next 14 App Router guidelines.
> 
> I use
> 
> ```json
>     "next-auth": "^5.0.0-beta.19",
>     "next": "^14.2.3",
> ```
> 
> You have to _properly_ split codebase to server/client part. According to Next 14 App Router guidelines.
> 
> So, guys, I got your back!
> 
> # Follow these steps
> ## 1. Create `current-session.ts` in `lib` folder.
> ```
> .
> ├── ...
> ├── app                  
> │   ├── components     # here you can store client side components
> └── lib
> ```
> 
> `lib/current-session.ts`
> 
> ```ts
> import { auth } from "@/auth";
> 
> /**
>  * Retrieves the current user from the authentication session.
>  *
>  * @return {Promise<User | undefined>} The current user if available, otherwise undefined.
>  */
> export const currentUser = async () => {
>   const session = await auth();
> 
>   return session?.user;
> };
> ```
> 
> This is our server side session user. Use in any component that supposed to work as server component (by default it is). For example **layout.tsx** or **page.tsx**
> 
> ## 2. Get user in any server component then pass to client component
> Important
> 
> For example, i use `<Navbar/>` in my `layout.tsx`. I have In Navbar user button `AuthButton` , so to actually update state of this button (load avatar, nickname, email) after sign-in or sign-up without refreshing page simply pass user to client component (in this case `AuthButton`).
> 
> `app/_components/Navbar.tsx`. I prefer to store server-side components in suffix-like folders `_components`
> 
> ```ts
> import {currentUser } from "@/lib/current-session";
> 
> export const Navbar = async () => {
>   // Get user from server side in layout (for example navbar)
>   const user = await currentUser();
> 
>   return (
>      <AuthButton user={user} />
>   );
> };
> ```
> 
> ## 3. Create `AuthButton.tsx` client component and get data from parent server component (`Navbar.tsx`).
> `app/components/AuthButton.tsx`
> 
> ```ts
> "use client";
> 
> interface AuthButtonProps {
>   user?: User
> }
> 
> export const AuthButton = ({
>   user,
> }: AuthButtonProps) => {
>   if (user) {
>       return (
>         <div>
>             <span>{user.image}</span>
>             <p>{user.email}</p>
>         </div>
>       );
>   }
>   return (
>      <p>Not logged in</p>
>   );
> };
> ```
> 
> Where user is type of default User. You can extend this via database model
> 
> ```ts
> type User = {
>     id: string;
>     image: string;
>     email: string;
>     // etc...
> }
> ```
> 
> Hope it helps, please write back if this works for you @weijyun9008 @lespons @78raoul78

Doesn't this cause your whole app to be dynamically rendered, instead of having static & dynamic pages?

**Comment by bartoszhernas** [comment]
I had the same issue with custom login page, adding this to custom login page fixed the issue for me (or hid it)

```
  const session = await auth();
  if (session) {
    redirect(searchParams?.callbackUrl ? decodeURIComponent(searchParams.callbackUrl) : '/');
  }
```

**Comment by Linger7** [comment]
Still facing this issue with the latest version of NextAuth and NextJs

**Comment by raghav-kokotree** [comment]
Here’s the workaround I implemented for handling the redirection along with the callback URL after login. I would appreciate feedback from the community and the developers of NextAuth.js to confirm whether this is a good approach.

#### On the Login Page (Page)

```js
import { useSearchParams } from 'next/navigation';

export default function LoginPage() {
  const searchParams = useSearchParams();
  const callbackUrl = searchParams.get('callbackUrl');

  return (
    <main className="flex items-center justify-center md:h-screen">
       {/* Other components */}
       <LoginForm callbackUrl={callbackUrl} />
       {/* Other components */}
    </main>
  );
}
```

#### Passing the `callbackUrl` to the Login Form (Component)

```js
export default function LoginForm({
  callbackUrl,
}: {
  callbackUrl: string | null;
}) {
  const [errorMessage, formAction, isPending] = useActionState(
    (prevState: string | undefined, formData: FormData) =>
      myLogin(prevState, formData, callbackUrl),
    undefined,
  );

  return (
    <form action={formAction}>
      {/* Form fields go here */}
    </form>
  );
}
```

#### Handling the Login Action (Server Component)

```js
export async function myLogin(
  prevState: string | undefined,
  formData: FormData,
  callbackUrl: string | null,
) {
  try {
    await signIn('credentials', formData);
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return 'Invalid credentials.';
        default:
          return 'Something went wrong.';
      }
    }
    throw error;
  } finally {
    const decodedCallbackUrl = callbackUrl
      ? decodeURIComponent(callbackUrl)
      : '/';
    redirect(decodedCallbackUrl);
  }
}
```

#### Redirect After Login

With this code, after a successful login, the user will be redirected to the `callbackUrl`:

```js
const decodedCallbackUrl = callbackUrl
  ? decodeURIComponent(callbackUrl)
  : '/';
redirect(decodedCallbackUrl);
```

**Comment by Peaverin** [comment]
For the record, still facing this issue as of today
```
"next": "14.2.14",
"next-auth": "^5.0.0-beta.22",
```
@lespons workaround worked for me

**Comment by ChrisDoufu** [comment]
The same thing happens when I try to sign out using the following code, that the page just stays where it is: 

`logout.tsx` with failed redirection
```tsx
export function Logout() {
  return (
    <form
      action={async () => {
        "use server";
        await signOut();
      }}
    >
      <button>Log out</button>
    </form>
  );
}
```

The expected behavior should be to redirect to a login page:

`auth.config.ts`
```tsx
export const authConfig = {
  pages: {
    signIn: "/login",
  },
  callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user;
      const isOnDashboard = nextUrl.pathname.startsWith('/dashboard');
      if (isOnDashboard) {
        if (isLoggedIn) return true;
        return false; // Redirect unauthenticated users to login page
      } else if (isLoggedIn) {
        return Response.redirect(new URL('/dashboard', nextUrl));
      }
      return true;
    },
  },
} satisfies NextAuthConfig;
```

It seems that you have to manually redirect it in the `finally` like this:

`logout.tsx` with successful redirection
```tsx
export function Logout() {
  return (
    <form
      action={async () => {
        "use server";
        try {
          await signOut();
        } catch (error) {
          throw error;
        } finally {
          redirect("/");
        }
      }}
    >
      <button>Log out</button>
    </form>
  );
}
```

**Comment by fqf** [comment]
In my case there wasn't redirection becase of next_redirect error was occured. The reason was in catch block where I didn't throw error object:
`catch (error) {
    return { success: false, message: "auth error" };
  } `
Note, you should have this part in the end of catch block:
`catch (error) {
    ................
   throw error;
  } `

**Comment by jabedzaman** [comment]
> I'm using **_next-auth@5.0.0-beta.22_** and in my case there wasn't redirection because of next_redirect error was occured. The reason was in catch block where I didn't throw error object:
> 
> ```ts
> try {
>   await signIn(......);
> } catch (error) {
>   return { success: false, message: "auth error" };
> }
> ```
> 
> Note, you should have this part in the end of catch block:
> 
> ```ts
> catch (error) {
>   ................
>   throw error;
> } 
> ```

even with this I am still facing this error

**Comment by CaioRigloski** [comment]
I was facing two issues: sign-in with  cookie-free browser the session was not updating, so none info was appearing until a page reload, and after a logout with a user and login with another one the previous user infos was showed. I fixed it with the code below
```
"next": "14.2.5",
"next-auth": "^5.0.0-beta.20"
```

`/app/sign-in/page.tsx`
```
import { checkCredentials } from "./actions"

// receive the username/email and password and check the credentials with NextAuth's SignIn function in server actions
async function updateSessionAndReload(values: SignInInterface) {
    await checkCredentials(values) //
    await session.update()
    window.location.reload()
  }
```

`/app/sign-in/actions.ts`
```
export async function checkCredentials(values: SignInInterface) {
// redirection done in middleware
  await signIn("credentials", {
    ...values,
  })
}
```

`/components/Header.tsx`
```
// sign-out executed in server actions
<form className="flex justify-end" action={signOutAction}>
        <Button type="submit">Sign Out</Button>
</form>
```

`/app/sign-out/actions.ts`
```
export async function signOutAction() {
  await signOut({ redirectTo: "/sign-in" })
}
```

`/app/api/auth/[nextauth]/route.ts`
```
async jwt({ token, trigger, user, session }) {
      if (trigger === "signIn" && user || trigger === "update" && user) {
        token.user = {id: user.id, username: user.username, profilePicture: user.profilePicture}
      }
      
      return token
    }
```

**Comment by cschroeter** [comment]
```tsx
  signIn('credentials', {
    username: formData.get('username'),
    password: formData.get('password'),
    redirectTo: formData.get('redierctTo')?.toString() ?? '/',
  })
  ```

**Comment by decoderid** [comment]
### NextAuthProvider
```tsx
'use client'

import type { Session } from "next-auth"
import { SessionProvider } from "next-auth/react"

export default function NextAuthSessionProvider({ children, session }: { children: React.ReactNode, session: Session | null }) {
    return <SessionProvider session={session}>{children}</SessionProvider>
}
```

### Actions
```ts
'use server';
 
import { signIn } from '@/auth';
import { AuthError } from 'next-auth';
 
export async function authenticate(
  prevState: string | undefined,
  formData: FormData,
) {
  try {
    const username = formData.get('username')
    const password = formData.get('password')
    const callbackUrl = formData.get('callbackUrl')
    await signIn('credentials', {
      username,
      password,
      redirect: true,
      redirectTo: String(callbackUrl)
    })
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return 'Invalid credentials.';
        default:
          return 'Something went wrong.';
      }
    }
    throw error;
  }
}
```
### LoginForm
```tsx
'use client'

import { useActionState } from "react"
import { authenticate } from "@/app/lib/actions"
import { useSearchParams } from "next/navigation"

export default function Page() {
    const [errorMessage, formAction, isPending] = useActionState(
        authenticate,
        undefined
    )

    const search = useSearchParams()
    const callbackUrl = search.get('callbackUrl') ?? '/'

    return (
        <form action={formAction} className="grid grid-cols-1 gap-4">
            <input type="text" name="username" defaultValue="super" />
            <input type="text" name="password" defaultValue="123456" />
            <input type="hidden" name="callbackUrl" defaultValue={callbackUrl} />
            <button type="submit">Login</button>
        </form>
    )
}
```

### I had to refresh page
https://github.com/user-attachments/assets/d7c66a7c-20e9-4dae-b209-3442bc3c27d5


### Npm Package
```log
├── @eslint/eslintrc@3.2.0
├── @types/node@20.17.10
├── @types/react-dom@19.0.2
├── @types/react@19.0.1
├── axios@1.7.9
├── eslint-config-next@15.1.0
├── eslint@9.16.0
├── next-auth@5.0.0-beta.25
├── next@15.1.0
├── postcss@8.4.49
├── react-dom@19.0.0
├── react@19.0.0
├── tailwindcss@3.4.16
├── typescript@5.7.2
└── zod@3.24.1
```

**Comment by Rov98** [comment]
still having an issue and my user return null.
and another issue is what if u want to redirect to dynamic router after successfully login?

`'use server'

import { auth, signIn } from "@/auth"
import { CredentialsSignin } from "next-auth";
import { redirect } from "next/navigation";

export async function handleSubmitForm(data: FormData) {
    try {
        await signIn("credentials", {
            redirect: false,
            email: data.get("email"),
            password: data.get("password"),
        });
    } catch (error: unknown) {
        if (error instanceof CredentialsSignin) {
            return {
                message: "wrong credentials",
                stack: error
            }
        }

        return {
            message: "wrong credentials"
        }
    }

    const user = await auth();
    console.log(user);
    redirect(`/${user?.user?.id}`);
}`

**Comment by Rov98** [comment]
> still having an issue and my user return null. and another issue is what if u want to redirect to dynamic router after successfully login?
> 

Found a solution. u need to handle it on different function and call this function when the handleSubmitForm is returning something, either it's client side or server side. it's also takes time for the jwt token to register in the cookies depends on your providers callback.

```

export async function handleSubmitForm(data: FormData) {
    try {
        await signIn("credentials", {
            redirect: false,
            email: data.get("email"),
            password: data.get("password"),
        });

        return {
            success: true,
            message: "login success"
        }
    } catch (error: unknown) {
        if (error instanceof CredentialsSignin) {
            return {
                success: false,
                message: "Email atau Password salah",
                stack: error
            }
        }

        return {
            success: false,
            message: "Email atau Password salah"
        }
    }
}

export async function handleRedirect() {
    const user = await auth();
    console.log(user);
}
```

**Comment by lazarusking** [comment]
So from what I've realized redirect is some kind of error in next, so without throw error the redirect doesn't happen
```js
try {
    await signIn("credentials", {
      ...formData,
      redirectTo: "/",
    });
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          return { error: "Invalid credentials!" };
        default:
          return { error: "Something went wrong!" };
      }
    }

    throw error;
  }
  ```

**Comment by jorbelca** [comment]
> So from what I've realized redirect is some kind of error in next, so without throw error the redirect doesn't happen
> 
> try {
>     await signIn("credentials", {
>       ...formData,
>       redirectTo: "/",
>     });
>   } catch (error) {
>     if (error instanceof AuthError) {
>       switch (error.type) {
>         case "CredentialsSignin":
>           return { error: "Invalid credentials!" };
>         default:
>           return { error: "Something went wrong!" };
>       }
>     }
> 
>     throw error;
>   }

I have experienced the same error, and if yout type the catch it works again

**Comment by abid211051** [comment]
`"use server";

import { AuthError } from "next-auth";
import { signIn } from "../auth/[...nextauth]/route";

export async function authenticate(prevState, formData) {
  try {
    await signIn("credentials", formData);
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          return "Invalid credentials.";
        default:
          return "Something went wrong.";
      }
    }
    throw error;
  }
}
`

In my case, auto redirection is worked by this "next Learn module" code. Nextauth return NEXT_REDIRECT error after successfull login.

**Comment by balazsorban44** [comment]
Hi folks, those of you who have wrapped `signIn` with a try..catch, be aware that you should use https://nextjs.org/docs/app/api-reference/functions/unstable_rethrow to avoid errors like `NEXT_REDIRECT`

**Comment by GrahamQuan** [comment]
> I actually finally made it work thanks to another very recent github issue (cannot find it anymore tho lol)
> 
> The underlying issue was that `next-auth`'s session provider doesn't update the session passed from auth() in client side, it only happens upon page refresh.
> 
> The solution was to build a custom `SessionProvider` that utilizes `getSession()` instead of `auth()` and passing it as a state onto `next-auth's` `SessionProvider`:
> 
> "use client";
> 
> import { Session } from "next-auth";
> import {
>     SessionProvider as NextSessionProvider,
>     getSession
> } from "next-auth/react";
> import { usePathname } from "next/navigation";
> import {
>     ReactNode,
>     useCallback,
>     useEffect,
>     useState
> } from "react";
> 
> // Retrieve user session for the app's session context
> export default function SessionProvider({
>     children
> }: {
>     children: ReactNode;
> }) {
>     const [ session, setSession ] = useState<Session | null>(null);
>     const pathName = usePathname();
> 
>     const fetchSession = useCallback(async () => {
>         try {
>             const sessionData = await getSession();
>             setSession(sessionData);
>         } catch (error) {
>             setSession(null);
> 
>             if (process.env.NODE_ENV === "development") {
>                 console.error(error);
>             }
>         }
>     }, []);
> 
>     useEffect(() => {
>         fetchSession().finally();
>     }, [fetchSession, pathName]);
> 
>     return (
>         <NextSessionProvider session={session}>
>             {children}
>         </NextSessionProvider>
>     );
> }
> Now I can use `useSession()` from `next-auth` just normally and I am returned the up-to-date session data after login. Now, I do not have to reload the entire app upon login / logout!!!
> 
> I am very happy as I finally figured this out, it's been plagueing me for almost 2 months by now.

thanks!

**Comment by 1saifj** [comment]
i will never upgrade to nextauth beta version ever again!!!

**Comment by khuezy** [comment]
Following this guide: https://authjs.dev/guides/pages/signin

I'm still getting the `Error: NEXT_REDIRECT`

**Comment by hira-iqbal** [comment]
I am facing same issue in production. Locally everything is fine.

**Comment by leccyril** [comment]
> I am facing same issue in production. Locally everything is fine.

Yarn build + yarn start locally to reproduce the issue, i face same issue i have 2 provider so in each login page set redirect false and in success redirect or router push does not redirect anywhere

**Comment by jonas-is-coding** [comment]
This looks like a type boundary problem rather than a runtime logic issue. The most reliable fix is to make the input/output contract explicit at the entry point, validate unknown data before it reaches typed code, and avoid widening to `any` in shared paths. If the failure appeared after an upgrade, pinning to the previous known-good version while narrowing the contract usually removes the regression without introducing hidden behavior changes.
