### ISSUE TITLE
PrismaClientKnownRequestError: Invalid `prisma.account.findUnique()

### ISSUE THREAD

**Issue by robalmeister** [nextauthjs/next-auth#10095]
### Adapter type

@auth/prisma-adapter

### Environment

packages on repo,
page in cloudflare pages

### Reproduction URL

https://github.com/robalmeister/next-auth-example/

### Describe the issue

I got error when I sign in,
error:
```
"logs": [
    {
      "message": [
        "\u001b[31m[auth][error]\u001b[0m AdapterError: Read more at https://errors.authjs.dev#adaptererror"
      ],
      "level": "error",
      "timestamp": 1708519171968
    },
    {
      "message": [
        "\u001b[31m[auth][cause]\u001b[0m:",
        "PrismaClientKnownRequestError: \nInvalid `prisma.account.findUnique()` invocation:\n\n\nCannot fetch data from service:\nReflect.get called on non-object\n    at ls.handleRequestError (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:19:7318)\n    at ls.handleAndLogRequestError (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:19:6409)\n    at ls.request (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:19:6123)\n    at async u (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:27:6030)\n    at async getUserByAccount (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:58434)\n    at async le.<computed> (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:98:56939)\n    at async _o (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:34479)\n    at async Ta (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:45774)\n    at async Ln (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:50317)\n    at async __next-on-pages-dist__/webpack/a2d47114b49e53b1e23ea20308ba21ec.js:3:27008"
      ],
      "level": "error",
      "timestamp": 1708519171968
    },
    {
      "message": [
        "\u001b[31m[auth][details]\u001b[0m:",
        "{}"
      ],
      "level": "error",
      "timestamp": 1708519171968
    },
    {
      "message": [
        "\u001b[31m[auth][error]\u001b[0m AdapterError: Read more at https://errors.authjs.dev#adaptererror"
      ],
      "level": "error",
      "timestamp": 1708519171968
    },
    {
      "message": [
        "\u001b[31m[auth][cause]\u001b[0m:",
        "PrismaClientKnownRequestError: \nInvalid `prisma.account.findUnique()` invocation:\n\n\nCannot fetch data from service:\nReflect.get called on non-object\n    at ls.handleRequestError (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:19:7318)\n    at ls.handleAndLogRequestError (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:19:6409)\n    at ls.request (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:19:6123)\n    at async u (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:27:6030)\n    at async getUserByAccount (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:58434)\n    at async le.<computed> (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:98:56939)\n    at async _o (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:34479)\n    at async Ta (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:45774)\n    at async Ln (__next-on-pages-dist__/webpack/f01553668ca173b4ecfc1e3dab7688a7.js:464:50317)\n    at async __next-on-pages-dist__/webpack/a2d47114b49e53b1e23ea20308ba21ec.js:3:27008"
      ],
      "level": "error",
      "timestamp": 1708519171968
    },
    {
      "message": [
        "\u001b[31m[auth][details]\u001b[0m:",
        "{}"
      ],
      "level": "error",
      "timestamp": 1708519171968
    }
  ],
```

### How to reproduce

try to signin, signin page: https://next-auth-example-3a7.pages.dev/api/auth/signin

### Expected behavior

Redirect to https://next-auth-example-3a7.pages.dev/

**Comment by panp2000** [comment]
I have the same problem GoogleProvider.
The problem seems to be the wrong argument when calling getUserByAccount in @auth/prisma-adapter.

But, I could not find the caller...

**Comment by ThangHuuVu** [comment]
This seems to be a Prisma issue, not with `next-auth`. Try running `prisma migrate dev` again - see if its help 👀

**Comment by robalmeister** [comment]
Sorry but it's error adapter don't prisma, cloudflare pages don't support getAsyncContexy

**Comment by panp2000** [comment]
> This seems to be a Prisma issue, not with `next-auth`. Try running `prisma migrate dev` again - see if its help 👀

Thank you @ThangHuuVu. I tried but unfortunately it didn't solve the problem.
I have tried the following

1. `npx prisma migrate reset`
2. `npx prisma migrate dev` --- an empty migration was created.
3. SignIn with GoogleProvider

Log:
```
prisma:error 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    provider_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerAccountId: "101257081926708536208",
      provider: "google"
    },
?   id?: String,
?   id_userId_provider_providerAccountId?: AccountIdUserIdProviderProviderAccountIdCompoundUniqueInput,
?   AND?: AccountWhereInput | AccountWhereInput[],
?   OR?: AccountWhereInput[],
?   NOT?: AccountWhereInput | AccountWhereInput[],
?   userId?: StringFilter | String,
?   type?: StringFilter | String,
?   provider?: StringFilter | String,
?   providerAccountId?: StringFilter | String,
?   refresh_token?: StringNullableFilter | String | Null,
?   refresh_token_expires_in?: IntNullableFilter | Int | Null,
?   access_token?: StringNullableFilter | String | Null,
?   expires_at?: IntNullableFilter | Int | Null,
?   token_type?: StringNullableFilter | String | Null,
?   scope?: StringNullableFilter | String | Null,
?   id_token?: StringNullableFilter | String | Null,
?   session_state?: StringNullableFilter | String | Null,
?   user?: UserRelationFilter | UserWhereInput
  },
  select: {
    user: true
  }
}

Unknown argument `provider_providerAccountId`. Available options are marked with ?.
[auth][error] AdapterError: Read more at https://errors.authjs.dev#adaptererror
[auth][cause]: PrismaClientValidationError: 
Invalid `prisma.account.findUnique()` invocation:

{
  where: {
    provider_providerAccountId: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
      providerAccountId: "101257081926708536208",
      provider: "google"
    },
?   id?: String,
?   id_userId_provider_providerAccountId?: AccountIdUserIdProviderProviderAccountIdCompoundUniqueInput,
?   AND?: AccountWhereInput | AccountWhereInput[],
?   OR?: AccountWhereInput[],
?   NOT?: AccountWhereInput | AccountWhereInput[],
?   userId?: StringFilter | String,
?   type?: StringFilter | String,
?   provider?: StringFilter | String,
?   providerAccountId?: StringFilter | String,
?   refresh_token?: StringNullableFilter | String | Null,
?   refresh_token_expires_in?: IntNullableFilter | Int | Null,
?   access_token?: StringNullableFilter | String | Null,
?   expires_at?: IntNullableFilter | Int | Null,
?   token_type?: StringNullableFilter | String | Null,
?   scope?: StringNullableFilter | String | Null,
?   id_token?: StringNullableFilter | String | Null,
?   session_state?: StringNullableFilter | String | Null,
?   user?: UserRelationFilter | UserWhereInput
  },
  select: {
    user: true
  }
}

Unknown argument `provider_providerAccountId`. Available options are marked with ?.
    at Cn (/app/node_modules/@prisma/client/runtime/library.js:116:5888)
    at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6510)
    at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6188)
    at _n.request (/app/node_modules/@prisma/client/runtime/library.js:123:5896)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:10871)
    at async getUserByAccount (webpack-internal:///(rsc)/./node_modules/@auth/prisma-adapter/index.js:45:29)
    at async acc.<computed> (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/init.js:175:24)
    at async Module.callback (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/callback/index.js:59:33)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:42:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:126:29)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63809
    at async eU.execute (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)
    at async eU.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1543:40)
    at async DevServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1463:28)
    at async DevServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:1856:24)
    at async DevServer.renderToResponseImpl (/app/node_modules/next/dist/server/base-server.js:1894:32)
    at async DevServer.pipeImpl (/app/node_modules/next/dist/server/base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:271:17)
    at async DevServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:807:17)
    at async /app/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/app/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:163:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:342:24)
    at async requestHandlerImpl (/app/node_modules/next/dist/server/lib/router-server.js:366:13)
    at async Server.requestListener (/app/node_modules/next/dist/server/lib/start-server.js:140:13)
[auth][details]: {}
```
Versions:
`next` 14.1.0
`next-auth` 5.0.0-beta.13
`@auth/prisma-adapter` 1.4.0

**Comment by ConstantinAlexuta** [comment]
Any solution here ?

**Comment by vanilla-dd** [comment]
is there any fix?

**Comment by aifirstd3v** [comment]
Why was this issue closed rather than resolved?

**Comment by mashwishi** [comment]
5 months after, no fix yet?

**Comment by jahangeer7704** [comment]
model Account {
  id                String @id @default(auto()) @map("_id") @db.ObjectId
  userId            String  @db.ObjectId
  type              String?
  provider          String?
  providerAccountId String?
  refresh_token     String? @db.String
  access_token      String? @db.String
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.String
  session_state     String?
 
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
 
  user User @relation(fields: [userId], references: [id], onDelete: Cascade)
 
  @@unique([provider, providerAccountId])
} i made my model like this ,the issue gone

**Comment by Gonzalomorales1001** [comment]
i fixed it in my package.json:

    "@auth/prisma-adapter": "1.6.0",
    
You should downgrade the prisma adapter version to 1.6.0

**Comment by zimonitrome** [comment]
> i fixed it in my package.json:
> 
> ```
> "@auth/prisma-adapter": "1.6.0",
> ```
> 
> You should downgrade the prisma adapter version to 1.6.0

This did not help me :/

I'm running a db with this schema in development (Windows):

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
 
  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]

  votes         Vote[]
  suggestions   Suggestion[]

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model VerificationToken {
  identifier String
  token      String
  expires    DateTime

  @@unique([identifier, token])
}

model Map {
  id              String            @id @default(cuid())
  name            String
  ...
}

....
```

The last table "Map" is gettable always, but in production (Linux) Account is not gettable:

```
[auth][error] AdapterError: Read more at https://errors.authjs.dev#adaptererror
[auth][cause]: PrismaClientKnownRequestError: 
Invalid `prisma.account.findUnique()` invocation:


The table `main.Account` does not exist in the current database.
    at _n.handleRequestError (/<path>/.output/server/node_modules/@prisma/client/runtime/library.js:122:6927)
    at _n.handleAndLogRequestError (/<path>/.output/server/node_modules/@prisma/client/runtime/library.js:122:6235)
    at _n.request (/<path>/.output/server/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/<path>/.output/server/node_modules/@prisma/client/runtime/library.js:131:9116)
    at async getUserByAccount (file:///<path>/.output/server/node_modules/@auth/prisma-adapter/index.js:223:29)
    at async acc.<computed> (file:///<path>/.output/server/node_modules/@auth/core/lib/init.js:165:24)
    at async Module.callback (file:///<path>/.output/server/node_modules/@auth/core/lib/actions/callback/index.js:43:33)
    at async AuthInternal (file:///<path>/.output/server/node_modules/@auth/core/lib/index.js:27:24)
    at async Auth (file:///<path>/.output/server/node_modules/@auth/core/index.js:109:34)
    at async file:///<path>/.output/server/chunks/runtime.mjs:13599:19
[auth][details]: {}
```

**Comment by seo17** [comment]
I has this issue because my supabase database instance was paused due to inactivity

**Comment by pushpakninave** [comment]
I changed the version from `^2.7.4` to
```json
"dependencies": {
    "@auth/prisma-adapter": "1.6.0"
}
```
It worked for me, Seems like the issue with newer version is not yet resolved.
