### ISSUE TITLE
Error connecting to Atlas database using provided example

### ISSUE THREAD

**Issue by timsoraro** [nextauthjs/next-auth#1108]
I'm not sure if it's a problem with next-auth or my configuration. I'm trying to implement this example repo https://github.com/nextauthjs/next-auth-example using mongodb.

I setup a mongo database on Atlas. These are my files:

.env

```
MONGO_URI=mongodb+srv://<username>:<password>@ xxxxxx.xxxxxx.mongodb.net/<dbname>
EMAIL_SERVER_HOST= emailhost
EMAIL_SERVER_PORT=emailport
EMAIL_SERVER_USER=apikey
EMAIL_SERVER_PASSWORD=emailserverpassword
EMAIL_FROM=email
```

Of course, I changed the real values.

/pages/api/[...nextauth].js

```
import NextAuth from "next-auth";
import Providers from "next-auth/providers";

const options = {
  providers: [
    Providers.Email({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: process.env.EMAIL_SERVER_PORT,
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD,
        },
      },
      from: process.env.EMAIL_FROM,
    }),
  ],
  database: {
    type: "mongodb",
    uri: process.env.MONGO_URI,
    w: "majority",
    useNewUrlParser: true,
    useUnifiedTopology: true,
    retryWrites: true,
    synchronize: true
  },
};

export default (req, res) => {
  console.log(process.env.MONGO_URI)
  NextAuth(req, res, options)
}
```
When running 'npm run dev` I get to the login page but when I submit an email address the browser stuck loading and it prints this:

```
mongodb+srv://<username>:<password>@ xxxxxx.xxxxxx.mongodb.net/<dbname>
API resolved without sending a response for /api/auth/session, this may result in stalled requests.
```

 and after some time the console then prints this:

```
https://next-auth.js.org/errors#adapter_connection_error
[next-auth][error][session_error] TypeError: Cannot destructure property 'manager' of 'connection' as it is null.
    at Object.<anonymous> (/Users/user/Downloads/nextauth-examples-master/node_modules/next-auth/dist/adapters/typeorm/index.js:102:9)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/Downloads/nextauth-examples-master/node_modules/next-auth/dist/adapters/typeorm/index.js:28:103)
    at _next (/Users/user/Downloads/nextauth-examples-master/node_modules/next-auth/dist/adapters/typeorm/index.js:30:194) 
https://next-auth.js.org/errors#session_error
[next-auth][error][adapter_connection_error] MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/Users/user/Downloads/nextauth-examples-master/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
} 
https://next-auth.js.org/errors#adapter_connection_error
(node:66120) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'manager' of 'connection' as it is null.
    at Object.<anonymous> (/Users/user/Downloads/nextauth-examples-master/node_modules/next-auth/dist/adapters/typeorm/index.js:102:9)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/Downloads/nextauth-examples-master/node_modules/next-auth/dist/adapters/typeorm/index.js:28:103)
    at _next (/Users/user/Downloads/nextauth-examples-master/node_modules/next-auth/dist/adapters/typeorm/index.js:30:194)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried many things but nothing helped,
I'll appreciate your help,

Thanks

**Comment by timsoraro** [comment]
I solved the issue by using a new user different than admin. But I don't see users' data being saved to my database.

**Comment by timsoraro** [comment]
I somehow solved the problem by adding:

```
const options = {
  site: process.env.NEXTAUTH_URL,
```

**Comment by balazsorban44** [comment]
@timsoraro which version of `next-auth` are you using?

**Comment by timsoraro** [comment]
I'm using "^3.1.0".

**Comment by timsoraro** [comment]
Okay, you are right, it's not that. I'm not really sure what solved it.

**Comment by timsoraro** [comment]
Okay I noticed that this will cause the problem I reported orginially:
```
database: {
    type: "mongodb",
    uri: process.env.MONGO_URI,
    w: "majority",
    useNewUrlParser: true,
    useUnifiedTopology: true,
    retryWrites: true,
    synchronize: true
  },
```

Which is solved by:
```
database: process.env.MONGO_URI,
```
But i got ot say it didn't work when I tried before (so maybe something in my URI got fixed?).

**Comment by centerjustified** [comment]
I am seeing the same issue with mongoDB hosted on Atlas.  @timsoraro does your URI just `mongodb+srv://user:password@xxxx.xxx.mongodb.net/db_name` or are you also including any other flags?  Because that doesn't seem to be solving it for me.

**Comment by timsoraro** [comment]
@centerjustified yep, just like that without any flags. Did you try using a new user that is not the admin (just throwing some ideas here)?

**Comment by centerjustified** [comment]
@timsoraro originally I was using an admin user.  Created a new next-auth user with access to just the one database.  That didn't solve the issue.  I appreciate you throwing out ideas.  Are you using the same user for your general data connections and your auth connections?

**Comment by timsoraro** [comment]
Yes. Throwing more ideas:

1. I also did `npm cache clean --force`.
2. I just noticed something weird, migrating the code to a different project it didn't work again until I deleted 2 passport packages in package.json. So maybe make sure you don't have conflicted packages?

**Comment by EnriqueL8** [comment]
I'm also getting this issue, could we reopen the issue?  I've tried:
- `database: process.env.DATABASE_URL` with `database: mongodb+srv://dev:password@xxxx.xxx.mongodb.net/mydatabase`
- `npm cache clean --force`

Any other ideas @timsoraro @centerjustified ? Thanks!
