### ISSUE TITLE
TypeError: r is not a function. When using Lazy NextAuth initialization.

### ISSUE THREAD

**Issue by Waylon-Firework** [nextauthjs/next-auth#11544]
### Environment

```
(base) waylon@macbook-pro-m1 auth % npx envinfo --system --binaries --browsers --npmPackages "{next,react,next-auth,@auth/*}"


Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y


  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 105.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 22.5.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.90
    Safari: 16.3
  npmPackages:
    next: 14.2.5 => 14.2.5 
    next-auth: ^5.0.0-beta.20 => 5.0.0-beta.20 
    react: ^18 => 18.3.1 
```

### Reproduction URL

https://github.com/Waylon-Firework/next-auth-lazy-init/tree/lazy-init

### Describe the issue

Call api will show error when using lazy init: http://localhost:3000/api/protected

<img width="712" alt="image" src="https://github.com/user-attachments/assets/157b67be-b561-42a8-b862-9e31a8ac676d">

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/9d0445aa-d243-45d9-a666-ece96f24e035">

### How to reproduce

call the api: http://localhost:3000/api/protected

### Expected behavior

no error

**Comment by bjedev** [comment]
I love not getting answers to vital questions.

**Comment by suitux** [comment]
Same issue here

**Comment by gadicc** [comment]
Had this issue with Next 14 but it works with Next 15.

Just make sure that you remember to **`await`** `auth(...)` otherwise you'll get 

```bash
 ⨯ [TypeError: Function.prototype.apply was called on #<Promise>, which is an object and not a function]
```

```diff
import { auth } from "@/auth"
import { NextResponse } from "next/server"
 
- export const GET = auth(function GET(req) {
+ export const GET = await auth(function GET(req) {
  if (req.auth) return NextResponse.json(req.auth)
  return NextResponse.json({ message: "Not authenticated" }, { status: 401 })
})
```

**Comment by noanflaherty** [comment]
@gadicc's solution worked for me. I had custom callbacks that looked like this:

```typescript
export const GET = auth(async (req) => {...});
```

And the issue was fixed upon changing them to:
```typescript
export const GET = await auth(async (req) => {...});
```

**Comment by contrun** [comment]
Are you guys using app router? What if my GET/POST handlers have signatures like

```
export const GET = async (
  _req: NextRequest,
  props: { params: Promise<{ nextauth: string[] }> },
) => {
}
```

I need to obtain the url parameter `nextauth` with the function parameter `props`. After wrapping the whole async with `auth`, I still have the same error ` ⨯ [TypeError: Function.prototype.apply was called on #<Promise>, which is an object and not a function]`.

**Comment by Cairo555** [comment]
**## [WORKING FIX] – NextAuth v5-beta + Next.js 15 app-router: “apply was called on #<Object>”**
*(tested on Windows 11, Node 20, next-auth@5.0.0-beta.29, next@15.4.4)*

If you get  
`TypeError: Function.prototype.apply was called on #<Object>, which is an object and not a function`  
when trying to use NextAuth v5-beta with the Next.js app-router, the fix is:

**DO NOT export the handler object directly.**  
Instead, destructure and export **ONLY** the `GET` and `POST` functions from the `handlers` property.

<details>
<summary>Minimal working example</summary>

```typescript
// app/api/auth/[...nextauth]/route.ts
import NextAuth from "next-auth";
import Credentials from "next-auth/providers/credentials";

const authResult = NextAuth({
  debug: true,
  providers: [
    Credentials({
      name: "Test",
      credentials: {
        username: { label: "Username", type: "text" },
        password: { label: "Password", type: "password" }
      },
      async authorize(credentials) {
        if (
          credentials?.username === "niels" &&
          credentials?.password === "test123"
        ) {
          return { id: "1", name: "Niels" };
        }
        return null;
      }
    })
  ]
});

// ONLY export GET and POST from the handlers property!
export const { handlers: { GET, POST } } = authResult;
```
</details>

And make sure you have a valid `.env.local` file:

```ini
AUTH_SECRET=yourRandomString
NEXTAUTH_URL=http://localhost:3000
```

- Restart your dev server after updating `.env.local`.
- Test `/api/auth/providers`. You should now see your providers, not a 500 error.
- This works with all providers and your real config as well!

---

**Summary:**  
If you export the whole object (`export { handler as GET, handler as POST }`), Next.js expects a function but gets an object, causing the `apply was called on #<Object>` error.  
By exporting only the `GET` and `POST` handlers as functions, the app-router works as intended with NextAuth v5-beta!

**Comment by ammaraslam10** [comment]
Still not fixed??

**Comment by hasnainXdev** [comment]
I am also facing this issue
Next.js version 16.0.1
`"next-auth": "^5.0.0-beta.30"`


`TypeError: Function.prototype.apply was called on #<Object>, which is an object and not a function`

**Comment by reherger** [comment]
> Had this issue with Next 14 but it works with Next 15.
> 
> Just make sure that you remember to **`await`** `auth(...)` if using lazy initialisation otherwise you'll get
> 
>  ⨯ [TypeError: Function.prototype.apply was called on #<Promise>, which is an object and not a function]
> import { auth } from "@/auth"
> import { NextResponse } from "next/server"
>  
> - export const GET = auth(function GET(req) {
> + export const GET = await auth(function GET(req) {
>   if (req.auth) return NextResponse.json(req.auth)
>   return NextResponse.json({ message: "Not authenticated" }, { status: 401 })
> })

In case your IDE keep warning you with "TS80007: await has no effect on the type of this expression."

Use Promise.all like this in proxy.ts:
`
const [proxy] = await Promise.all([
  auth(async req => {
  ...
  }),
])
`

**Comment by hasnainXdev** [comment]
> > Had this issue with Next 14 but it works with Next 15.
> > Just make sure that you remember to **`await`** `auth(...)` if using lazy initialisation otherwise you'll get
> > ⨯ [TypeError: Function.prototype.apply was called on #, which is an object and not a function]
> > import { auth } from "@/auth"
> > import { NextResponse } from "next/server"
> > 
> > * export const GET = auth(function GET(req) {
> > 
> > 
> > * export const GET = await auth(function GET(req) {
> >   if (req.auth) return NextResponse.json(req.auth)
> >   return NextResponse.json({ message: "Not authenticated" }, { status: 401 })
> >   })
> 
> In case your IDE keep warning you with "TS80007: await has no effect on the type of this expression."
> 
> Use Promise.all like this in proxy.ts: `const [proxy] = await Promise.all([ auth(async req => { ... }), ])`

okay thanks for the help, now I'm using betterauth for now, but for full customization I'll go with nextauth

**Comment by jonas-is-coding** [comment]
This looks like a type boundary problem rather than a runtime logic issue. The most reliable fix is to make the input/output contract explicit at the entry point, validate unknown data before it reaches typed code, and avoid widening to `any` in shared paths. If the failure appeared after an upgrade, pinning to the previous known-good version while narrowing the contract usually removes the regression without introducing hidden behavior changes.
