### ISSUE TITLE
Non-Semver dependency on legacy-adapter packages caused upgrade headache

### ISSUE THREAD

**Issue by zackdotcomputer** [nextauthjs/next-auth#2008]
## Description 🐜 and Cause

> Edit: initially, this issue was about the documentation regarding the use of legacy-adapters because I believed the prisma legacy adapter was broken. Now that Balasz pointed me in the right direction for debugging it, I've updated it to reflect the actual issue.

Upgrading across a boundary where the dependency on the legacy adapter packages was also upgraded can cause build failures for end-developers. An example of this occurred for people upgrading from 3.20.0 to 3.20.1 who depended on the legacy prisma adapter. Here's how:

This `next-auth` package depends on `"@next-auth/prisma-legacy-adapter": "canary"` however between the two versions listed above, the package.lock updated _which_ canary from `canary-115` to `canary-127`. Because the dependency in the package.json just states "canary", though, downstream yarn consumers who upgraded across that boundary encountered a failure. Their dependency graph appeared to satisfy the requirements (because "canary" was installed), but the versions of canary had slightly different APIs and so were incompatible.

A clean install of 3.21.1 will succeed in all situations, but users who upgrade got a broken experience unless they manually deleted that one dependency from their yarn.lock (or deleted the lock file entirely).

The proposed solution to this is to move the `@next-auth/*-adapter` packages over to using a proper semver rather than the tag `canary`. That way, upgrades to the packages would properly flow to us end-developers.

## How to reproduce ☕️

See [this comment](https://github.com/nextauthjs/next-auth/issues/2008#issuecomment-841797746) for investigation into how to cause this issue.

## Screenshots / Logs 📽

Calls to the [...nextauth].ts endpoint produce the following error:

```
TypeError: next_auth_adapters__WEBPACK_IMPORTED_MODULE_2___default(...).Prisma.Adapter is not a function
```

## Environment 🖥

```
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 706.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/code/traveler/tweetsweep/node_modules/.bin/yarn
    npm: 7.9.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0
    Safari: 14.1
```

**Comment by balazsorban44** [comment]
No need to report the same issue twice, it creates overhead.

Could you please provide a reproduction?

**Comment by zackdotcomputer** [comment]
Hey @balazsorban44, sorry to be clear issue 93 in the other repo was about the non-functionality (since that was where the code for legacy-prisma lives). This issue was meant to be about the documentation being incongruous between what the guide tells developers to do and what the README in the other repo tells developers to do.

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/issues/1987 had a similar problem, turned out the problem was in their side. I have thoroughly tested the Prisma adapter with both the typescript and javascript example, with 3 different import styles, so in all 6 different cases. It worked fine in each case. Without a reproduction, I don't know how to help

**Comment by balazsorban44** [comment]
The new adapter is recommended for newer projects, but as you can see it is still a work in progress. The legacy adapter (the one you import from `next-auth/adapters`) should be working as before, only the source code moved.

**Comment by zackdotcomputer** [comment]
Ok - the pointer to that other issue is helpful and I've tracked down what goes wrong:

The issue reproduces if you have an app that is using `next-auth@3.21.0` or before and you upgrade to `3.21.1` or later. I ran into this issue using `yarn` - will have to test separately whether `npm` produces the same issue.

The package depends on `"@next-auth/prisma-legacy-adapter": "canary"` however between those two versions the `package.lock` updated **which** canary from 115 to 127. However, because the dependency just states "canary", downstream yarn consumers who upgrade across that boundary encounter this error. Their dependency graph appears to satisfy the requirements (because "canary" is installed), but the versions of canary are not actually API-compatible.

A clean install of 3.21.1 will succeed in all situations, but users who upgrade will get a broken experience unless they manually delete that one dependency from their `yarn.lock` or they blow away their lock file entirely (obviously not a thing you want to have to do when trying to upgrade reps responsibly).

I think the cleanest way to fix this is to move the `@next-auth/*-adapter` packages over to using a proper semver versioning system. That way, upgrades to the packages would properly flow to us end-developers.

**Comment by zackdotcomputer** [comment]
I still find the documentation vs README confusing, but I agree that there is [no contradiction](https://github.com/nextauthjs/next-auth/issues/2008#issuecomment-841796279) and certainly not an urgent one given the discovery of what was causing the build to break.

**Comment by zackdotcomputer** [comment]
I updated the title and description to reflect where our discussion landed. Even though this bug has been fixed locally thanks to these discoveries, I think this issue should stay open since the problem will reoccur next time there's a breaking change to the legacy adapters unless they are moved to semver numbers.

**Comment by balazsorban44** [comment]
I see. It boils down to that I misunderstood how `canary` as a version would work... In the migration process, I wanted to make sure that iterating on issues of the legacy adapters wouldn't require the users to upgrade `next-auth` (as in I didn't want to create a lot of new patch versions). I guess it would have bene the correct way after all.

So you think pinning down a version of the canary adapters and creating a patchin `next-auth` every time something changed in the legacy adapters would solve this?

Unfortunately, I don't think we can fix it backwards though. 😕

**Comment by zackdotcomputer** [comment]
I don't think we need to fix it backwards (though maybe it would be good to add a note to the [3.21.1 release note](https://github.com/nextauthjs/next-auth/releases/tag/v3.21.1) that links here so people are aware of it).

Yeah, this is new learning for me about how yarn resolves second level dependencies! I also would've assumed it would use the lock file from your project or that at worst it would be a non-breaking migration, but the evidence appears otherwise.

I do think that the best solution would be:
1. Use numerical versions for the adapters (probably just using 0.X.X values conveys the same meaning as "canary")
2. Pin `next-auth`'s dependency in `package.json` (not just the lockfile) to be a specific number version
3. When you want to upgrade the version next-auth uses, upgrade it in both the package.json and package-lock.json.

I'm 99.9% sure that will stop this from ever happening again...

And no worries on the research - thanks for listening even though we got off to a rough start when I was kinda panicked to have my auth layer break this morning 😓

**Comment by balazsorban44** [comment]
Versioning is hard I guess. 😳

I'll revisit your suggestions, it is a very small change on our side.

About the contradiction in the documentation, I'm still not sure what (if anything) should change. Do you have a direct suggestion to make it more clear?

I do plan on creating a uniform README for the adapters in the other repo, but currently busy with writing tests (so we could ship with more confidence 🥳)
