### ISSUE TITLE
Using middleware results in INVALID_CALLBACK_URL_ERROR

### ISSUE THREAD

**Issue by hankolsen** [nextauthjs/next-auth#4700]
### Environment

  System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 348.10 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 101.0
    Safari: 15.5
  npmPackages:
    next: ^12.0.11-canary.4 => 12.1.6 
    next-auth: latest => 4.4.0 
    react: ^17.0.2 => 17.0.2 

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

Using next-auth middleware with the latest version of Next (currently 12.1.6) doesn't work.

The callbackUrl of `withAuth` is a relative URL. However, v12.0.9 of Next added "Enforce absolute URLs in Edge Runtime [PR](https://github.com/vercel/next.js/pull/33410)"

Navigating to a page that is protected by middleware results in the user being redirected to `http://localhost:3000/api/auth/signin?callbackUrl=%2Fadmin` and an error message in the browser:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/1008390/173197004-07823d3c-3506-4521-b4e1-81ff157fd993.png">

### How to reproduce

Steps to reproduce:
1. Clone the next-auth-example repository
2. Add a NEXTAUTH_SECRET in `.env.local`
3. Start the dev server
4. Go to localhost:3000 and click `Admin`
 
Result: 
Server error. 
The server log shows
```https://next-auth.js.org/errors#invalid_callback_url_error Invalid callback URL. Received: /admin InvalidCallbackUrl: Invalid callback URL. Received: /admin```

### Expected behavior

There should be a login form and no server errors.

**Comment by hankolsen** [comment]
Changing line 123 of [middleware.ts](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/next/middleware.ts) from
```javascript
signInUrl.searchParams.append("callbackUrl", `${req.nextUrl.pathname}${req.nextUrl.search}`)
```
to
```javascript
signInUrl.searchParams.append("callbackUrl", `${req.nextUrl.href}${req.nextUrl.search}`)
```
works, however, I'm not sure if using `req.nextUrl.href` is the correct solution

**Comment by cbyrneee** [comment]
Also having this problem.

**Comment by callumok2004** [comment]
I am also experiencing this issue, need a working fix asap

**Comment by balazsorban44** [comment]
This should be fixed in `4.5.0`, please give it a try and let us know!

**Comment by hankolsen** [comment]
Yep, works as expected!
Thanks @balazsorban44!

**Comment by yanickrochon** [comment]
I started seeing this problem today. There were no errors before. As a sole programmer on a mid-size project, this does not make my morning a pleasant one. I tried debugging the issue, but the error still happens _**multipe times**_ when the custom sign-in page is hit. Why would this error happen _**multiple times**_ on a single request, even when a `callbackUrl` argument is specified?

**Comment by danvernon** [comment]
> I started seeing this problem today. There were no errors before. As a sole programmer on a mid-size project, this does not make my morning a pleasant one. I tried debugging the issue, but the error still happens _**multipe times**_ when the custom sign-in page is hit. Why would this error happen _**multiple times**_ on a single request, even when a `callbackUrl` argument is specified?

did you find an answer? just started happening to me randomly

**Comment by yanickrochon** [comment]
@danvernon my conclusion is that the `signOut` method is not clearning the cookie properly because clearing the cookie from the browser (through the dev console) removes this error. Next Auth should do a better job at validating it's content before validating.

**Comment by rachmadideni** [comment]
@yanickrochon Thanks. after searching for the solutions for several hours. finally, this fixes my issue.
