### ISSUE TITLE
TypeScript issues in session callback

### ISSUE THREAD

**Issue by lionelrudaz** [nextauthjs/next-auth#7132]
### Environment

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 604.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    Yarn: 3.3.0 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Safari: 16.2

### Reproduction URL

https://github.com/lionelrudaz/tasters/tree/release

### Describe the issue

I've not done any change on my environment lately, but I have a build error with the latest version of Next.

Here it is:

```
Type error: Property 'id' does not exist on type '{ name?: string; email?: string; image?: string; }'.

  136 |         // Add property to session, like an access_token from a provider.
  137 |         //console.log("Session callback", session, token, user)
> 138 |         session.user.id = token.sub;
      |                      ^
  139 |         session.user.isAdmin = token.isAdmin;
  140 |         session.user.vendorId = token.vendorId;
  141 |         session.user.stripe_id = token.stripeId;
```

This is in the session callback method.

Here's the complete method:

```
/**
       * @param  {object} session      Session object
       * @param  {object} token        User object    (if using database sessions)
       *                               JSON Web Token (if not using database sessions)
       * @return {object}              Session that will be returned to the client
       */
      async session({ session, token, user }) {
        // Add property to session, like an access_token from a provider.
        //console.log("Session callback", session, token, user)
        session.user.id = token.sub;
        session.user.isAdmin = token.isAdmin;
        session.user.vendorId = token.vendorId;
        session.user.stripe_id = token.stripeId;
        return session
      },
```

This is my next-auth.d.ts file:

```
import NextAuth, { DefaultSession } from "next-auth"
import { JWT } from "next-auth/jwt"
import type UserType from "./user"

declare module "next-auth" {
  /**
   * Returned by `useSession`, `getSession` and received as a prop on the `SessionProvider` React Context
   */
  interface Session {
    user: UserType & DefaultSession["user"]
  }

  interface User {
    image?: string
    isAdmin?: boolean
    vendorId?: number
    stripeId?: string
  }
}

declare module "next-auth/jwt" {
  /** Returned by the `jwt` callback and `getToken`, when using JWT sessions */
  interface JWT {
    /** OpenID ID Token */
    idToken?: string
    isAdmin?: boolean
    vendorId?: number
    stripeId?: string
  }
}
```

Nothing really different from the documentation.

I've checked my code, looks like session is from type DefaultSession and not Session anymore. I have no clue why.

I've tried to implement a DefaultSession interface, no luck...

My file was in /interfaces/next-auth.d.ts, I've moved it in /types like in https://next-auth.js.org/getting-started/typescript, no luck.

Here's my tsconfig.js file:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

I've checked the docs over and over, there must be something silly that has changed in a recent version, I just don't get it. It looks like it's a different issue than https://github.com/nextauthjs/next-auth/discussions/7033 encountered by @krinklesaurus and @arnekolja.

What I understand is that now in the session() callback, the type is DefaultSession instead of Session. Which means my interface is not used anymore. No idea why it stopped working all the sudden.

Let me know if there's anything useful I can add.

### How to reproduce

Explained above.

### Expected behavior

Extend the session with additional attributes.

**Comment by jonathanwilke** [comment]
Same problem for me

**Comment by ChristianIvicevic** [comment]
I can confirm a similar regression moving from `4.20.1` to `4.21.0`. Just like the T3 template I used to augment the `Session` type as follows:
```ts
import type { DefaultSession } from 'next-auth';

declare module 'next-auth' {
  interface Session {
    user: DefaultSession['user'] & {
      id: string;
    };
  }
}
```
During build I get this error attempting to write to the `session.user.id` object in the `session` callback of the configuration:
```
Type error: Property 'id' does not exist on type '{ name?: string | null | undefined; email?: string | null | undefined; image?: string | null | undefined; }'.
```
Thus it's likely the signature of that callback has a breaking change.

**Comment by madhurjain** [comment]
@balazsorban44 please take a look

**Comment by ChristianIvicevic** [comment]
> @balazsorban44 please take a look

Don't randomly ping maintainers. They will check out the issue once they have time. Also it's Sunday evening/night for most of the world right now.

**Comment by mauriciomutte** [comment]
Same problem for me 😕

**Comment by lionelrudaz** [comment]
> I can confirm a similar regression moving from 4.20.1 to 4.21.0. Just like the T3 template I used to augment the Session type as follows:

What's funny is that I was running an older version when the problem appeared, something like 4.10, so my first reflex was to update to 4.21.0 😅

Should we stick to 4.20.1 until there's a fix or a documented workaround for 4.21.0?

Thanks in advance folks

**Comment by balazsorban44** [comment]
Thanks for the heads up. Technically, the incoming `session` param has always been `DefaultSession` as can be seen here:

https://github.com/nextauthjs/next-auth/blob/c0bf2f15fb955d309d74f7eaf0b7e60968b0bb60/packages/next-auth/src/core/routes/session.ts#L64-L71

and here:

https://github.com/nextauthjs/next-auth/blob/c0bf2f15fb955d309d74f7eaf0b7e60968b0bb60/packages/next-auth/src/core/routes/session.ts#L137-L142

So actually the typing is more correct now.

Only the return type of the session callback is of type `Session`.

Maybe the true problem is that we've been recommending mutating the incoming param instead of creating a new object on return, so from the top of this thread, this:

```ts
async session({ session, token, user }) {
  // Add property to session, like an access_token from a provider.
  //console.log("Session callback", session, token, user)
  session.user.id = token.sub;
  session.user.isAdmin = token.isAdmin;
  session.user.vendorId = token.vendorId;
  session.user.stripe_id = token.stripeId;
  return session
},
```

should be this:

```ts
session({ session, token }) {
  return { ...session,
    user: { ...session.user,
      id: token.sub,
      isAdmin: token.isAdmin,
      vendorId: token.vendorId,
      stripe_id: token.stripeId
    }
  }
},
```

I understand it's breaking the current behavior though, so tagging @ThangHuuVu for thoughts, maybe we should revert after all to be less disruptive, even though it's kind of a small lie in the session param type.

Open to feedback and thoughts.


_NOTE: Please don't comment "same issue" or anything if it has no constructive meaning to the issue. It creates noise. If it's relevant to you, always hit the :+1: on the top post._

**Comment by juliusmarminge** [comment]
I think this is fair, and I just changed to the object-spread method and it works.

If it's the type that's actually passed, I think it should stay and update documentation to show this new way of module augmentation. The problem is it came out of nowhere without any documentation notice in a minor release that this behavior had been changed.

**Comment by ChristianIvicevic** [comment]
I want to share two relevant things to keep in mind regarding your mention of creating a new object instead of mutating it.

The first one is technical in nature and relates to the developer ergonomics. Since `session` is still of a type that is not augmented with manual types. This would probably (haven't tested it yet) prevent the convenient use of `immer` for example. Arguably the amount of objects to be spread isn't too bad but the use of `immer` may have been handy especially considering according to the docs it's technically required to test for the existence of `session.user`. I personally have this in my code:

```ts
session: ({ session, user }) => {
  if (session.user !== undefined) {
    session.user.id = user.id;
  }
  return session;
},
```

The second point relates to the widespread use of the current of handling things. @juliusmarminge already mentioned this in the PR he posted while I was still drafting this answer, but the create-t3-app is quite popular, being promoted by influencers etc. Many fresh developers with less experience will have picked it up and not necessarily expect such an unfortunate breaking change to begin with which may cause friction in downstream packages so to speak.

Hope these thoughts are of value to your decision process on how to move forward with that particular issue :)

**Comment by balazsorban44** [comment]
> The problem is it came out of nowhere without any documentation notice in a minor release that this behavior had been changed.

We do state we don't consider type changes breaking https://next-auth.js.org/getting-started/typescript#contributing

But I guess this take does not age well, so I'll stop doing it from now on... Sorry for the inconvenience... 🙏 :green_heart: 

Regarding:

```ts
session: ({ session, user }) => {
  if (session.user !== undefined) {
    session.user.id = user.id;
  }
  return session;
}
```

This would never evaluate to false in `if`, because [as shown](https://github.com/nextauthjs/next-auth/issues/7132#issuecomment-1493924161), `session` is a hardcoded object! So you can see how the current type might advertise false behavior. Honestly, if it's in the docs, it's likely because even _I_ was tripped by this when I took over maintaining the lib, and it just stuck...

Anyway, revert it is, then! We can correct this in `@auth/core` instead and explain it better in the migration guide/docs

**Comment by balazsorban44** [comment]
I pushed the fix, it's released in `4.21.1`!

**Comment by lionelrudaz** [comment]
Thanks a lot for the quick fix @balazsorban44, it works well.

I've noticed also that isNewUser is becoming deprecated in the jwt fallback. I know it should be a separate issue, but sometimes for makers like I am, we're no professional devs and keeping up with breaking changes in libraries we use is pretty hard. 

I can only imagine how hard it is at your end to make a library like this live, but I believe sometimes having an updated documentation and more complete release notes help us locate if there's an issue with a new version. Perhaps what I'm saying is non sense, but I definitely value the clarity of the documentation, which is BTW one of the asset of next-auth.

Anyway, if you need a hand documenting a change or another, I can try. Otherwise, keep on the good work, thanks a lot for this amazing library.

**Comment by Arro** [comment]
I'm using the sveltekit wrapper for this.  How would I get these changes into that?

**Comment by mikhail-karan** [comment]
> I'm using the sveltekit wrapper for this. How would I get these changes into that?

Also using SvelteKit wrapper and still seeing these errors.

**Comment by gusvianadev** [comment]
I have 4.22.1 and this is still happening
Session is extending DefaultSession, in which user doesn't have an id

**Comment by robreinhard** [comment]
Just wanted to confirm that I am also seeing this happen in 4.22.1

**Comment by udos86** [comment]
Also dealing with this in SvelteKit.

Here is my current workaround using type imports from the module augmentation:

```src/hooks.server.ts```

```ts
import type { Session, User } from "@auth/core/types";
```

```ts
session(params) {
    const session: Session = params.session;
    const user: User = params.user;

    session.user!.permissions = user.permissions;
    return session;
}
```

```src/types/auth.d.ts```

```ts
import { DefaultSession } from '@auth/core/types';

declare module '@auth/core/types' {
	interface Session {
		user?: {
			id?: string;
			permissions?: string[];
		} & DefaultSession['user'];
	}
	interface User {
		permissions?: string[];
	}
}
```

**Comment by developedbytoby** [comment]
Wondering if there's any progress on this. I'm running into this same issue on version 4.22.3

**Comment by mohamedamara1** [comment]
4.23.1 and this still occurs

**Comment by jzf21** [comment]
any workaround for this?

**Comment by pongbao** [comment]
haven't figured out anything as well -- 4.23.1

**Comment by jpcmf** [comment]
Same issue here on version 4.23.1

**Comment by geralddugbatey** [comment]
using version 4.24.1 and this worked for me 
`session({ session, token }) {
      return {
        ...session,
        user: {
          ...session.user,
          role: token.role,
        },
      };
    },`
adding a role to my session and this worked as previously stated above--> https://github.com/t3-oss/create-t3-app/pull/1330

**Comment by doneumark** [comment]
having the same issue here

**Comment by LegendNihal** [comment]
I found the main problem here. When you hover over user on the left side one  `session.user.id = user.id;`  you can see user is adapterUser which is only available if strategy is set to database. Since we are using Prisma and Prisma doesn't run on Edge runtime, we had to set strategy to jwt. Thats why `user.id` is undefined.

**Comment by Raulj123** [comment]
How do you fix this then?
<img width="378" alt="Screenshot 2024-01-15 at 11 27 11 AM" src="https://github.com/nextauthjs/next-auth/assets/112786129/62ae25dd-9ec1-42a3-9b66-89c1527ff8fd">

**Comment by koitoror** [comment]
> How do you fix this then? <img alt="Screenshot 2024-01-15 at 11 27 11 AM" width="378" src="https://private-user-images.githubusercontent.com/112786129/296854654-62ae25dd-9ec1-42a3-9b66-89c1527ff8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTMyOTQsIm5iZiI6MTcwNTYxMjk5NCwicGF0aCI6Ii8xMTI3ODYxMjkvMjk2ODU0NjU0LTYyYWUyNWRkLTllYzEtNDJhMy05YjY2LTg5YzE1MjdmZjhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RiZWRkOGQ0ZmY2YTEzZTk2ZTY0MjhiYzk0ZWEwZGQ2ZmJmOTE1MmNhYjhmMDY1ZjM4NDQxMGFjYTdkMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fptt57aQNiWxvkl76wrvf2JwzDbFTHq1T9WYKnsRI8c">

+1  i experienced the same below 
![image](https://github.com/nextauthjs/next-auth/assets/35098691/82b095c0-cc56-44bb-9f5a-d3cd4e8e86dc)

**Comment by anthoguille** [comment]
> > How do you fix this then? <img alt="Screenshot 2024-01-15 at 11 27 11 AM" width="378" src="https://private-user-images.githubusercontent.com/112786129/296854654-62ae25dd-9ec1-42a3-9b66-89c1527ff8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTMyOTQsIm5iZiI6MTcwNTYxMjk5NCwicGF0aCI6Ii8xMTI3ODYxMjkvMjk2ODU0NjU0LTYyYWUyNWRkLTllYzEtNDJhMy05YjY2LTg5YzE1MjdmZjhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RiZWRkOGQ0ZmY2YTEzZTk2ZTY0MjhiYzk0ZWEwZGQ2ZmJmOTE1MmNhYjhmMDY1ZjM4NDQxMGFjYTdkMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fptt57aQNiWxvkl76wrvf2JwzDbFTHq1T9WYKnsRI8c">
> 
> +1 i experienced the same below ![image](https://private-user-images.githubusercontent.com/35098691/297887380-82b095c0-cc56-44bb-9f5a-d3cd4e8e86dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzMzMzMsIm5iZiI6MTcwNTczMzAzMywicGF0aCI6Ii8zNTA5ODY5MS8yOTc4ODczODAtODJiMDk1YzAtY2M1Ni00NGJiLTlmNWEtZDNjZDRlOGU4NmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA2NDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTc5YzEyMDcwMTAyNGJmZmQ4Y2M0MzEyNzQ2OTMzNzY4NmRmZTUyMmI3ZmVkZWU4NjE3MGY5YzNjOTdiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CHu2Lha_a1sTHZD228UkAHKx3lPEZQ3S--ngEMWnqzk)

I couldn't find a solution.
![Captura de pantalla 2024-01-20 080316](https://github.com/nextauthjs/next-auth/assets/63469220/ba85092d-5256-4be8-9c89-a224b16f1e3a)

**Comment by tranhuyviet** [comment]
> > > How do you fix this then? <img alt="Screenshot 2024-01-15 at 11 27 11 AM" width="378" src="https://private-user-images.githubusercontent.com/112786129/296854654-62ae25dd-9ec1-42a3-9b66-89c1527ff8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTMyOTQsIm5iZiI6MTcwNTYxMjk5NCwicGF0aCI6Ii8xMTI3ODYxMjkvMjk2ODU0NjU0LTYyYWUyNWRkLTllYzEtNDJhMy05YjY2LTg5YzE1MjdmZjhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RiZWRkOGQ0ZmY2YTEzZTk2ZTY0MjhiYzk0ZWEwZGQ2ZmJmOTE1MmNhYjhmMDY1ZjM4NDQxMGFjYTdkMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fptt57aQNiWxvkl76wrvf2JwzDbFTHq1T9WYKnsRI8c">
> > 
> > 
> > +1 i experienced the same below ![image](https://private-user-images.githubusercontent.com/35098691/297887380-82b095c0-cc56-44bb-9f5a-d3cd4e8e86dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzMzMzMsIm5iZiI6MTcwNTczMzAzMywicGF0aCI6Ii8zNTA5ODY5MS8yOTc4ODczODAtODJiMDk1YzAtY2M1Ni00NGJiLTlmNWEtZDNjZDRlOGU4NmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA2NDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTc5YzEyMDcwMTAyNGJmZmQ4Y2M0MzEyNzQ2OTMzNzY4NmRmZTUyMmI3ZmVkZWU4NjE3MGY5YzNjOTdiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CHu2Lha_a1sTHZD228UkAHKx3lPEZQ3S--ngEMWnqzk)
> 
> I couldn't find a solution. ![Captura de pantalla 2024-01-20 080316](https://private-user-images.githubusercontent.com/63469220/298283472-ba85092d-5256-4be8-9c89-a224b16f1e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODc1OTMsIm5iZiI6MTcwNTc4NzI5MywicGF0aCI6Ii82MzQ2OTIyMC8yOTgyODM0NzItYmE4NTA5MmQtNTI1Ni00YmU4LTljODktYTIyNGIxNmYxZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIxNDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDZlNWFmY2UyOWI1NTRhMWMwMzdkYmNmNzBlMGQ2ZDBmNjc3MDBkNTBmM2M2NjY4ODQzMTZjZGRkNDYxZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vv19btJOyROvv3RA50FKeTl_w-9LF-doD_SQAUVCq2s)

you try to use the version: "next-auth": "^5.0.0-beta.4",

**Comment by koitoror** [comment]
> > > > How do you fix this then? <img alt="Screenshot 2024-01-15 at 11 27 11 AM" width="378" src="https://private-user-images.githubusercontent.com/112786129/296854654-62ae25dd-9ec1-42a3-9b66-89c1527ff8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTMyOTQsIm5iZiI6MTcwNTYxMjk5NCwicGF0aCI6Ii8xMTI3ODYxMjkvMjk2ODU0NjU0LTYyYWUyNWRkLTllYzEtNDJhMy05YjY2LTg5YzE1MjdmZjhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RiZWRkOGQ0ZmY2YTEzZTk2ZTY0MjhiYzk0ZWEwZGQ2ZmJmOTE1MmNhYjhmMDY1ZjM4NDQxMGFjYTdkMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fptt57aQNiWxvkl76wrvf2JwzDbFTHq1T9WYKnsRI8c">
> > > 
> > > 
> > > +1 i experienced the same below ![image](https://private-user-images.githubusercontent.com/35098691/297887380-82b095c0-cc56-44bb-9f5a-d3cd4e8e86dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzMzMzMsIm5iZiI6MTcwNTczMzAzMywicGF0aCI6Ii8zNTA5ODY5MS8yOTc4ODczODAtODJiMDk1YzAtY2M1Ni00NGJiLTlmNWEtZDNjZDRlOGU4NmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA2NDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTc5YzEyMDcwMTAyNGJmZmQ4Y2M0MzEyNzQ2OTMzNzY4NmRmZTUyMmI3ZmVkZWU4NjE3MGY5YzNjOTdiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CHu2Lha_a1sTHZD228UkAHKx3lPEZQ3S--ngEMWnqzk)
> > 
> > 
> > I couldn't find a solution. ![Captura de pantalla 2024-01-20 080316](https://private-user-images.githubusercontent.com/63469220/298283472-ba85092d-5256-4be8-9c89-a224b16f1e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODc1OTMsIm5iZiI6MTcwNTc4NzI5MywicGF0aCI6Ii82MzQ2OTIyMC8yOTgyODM0NzItYmE4NTA5MmQtNTI1Ni00YmU4LTljODktYTIyNGIxNmYxZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIxNDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDZlNWFmY2UyOWI1NTRhMWMwMzdkYmNmNzBlMGQ2ZDBmNjc3MDBkNTBmM2M2NjY4ODQzMTZjZGRkNDYxZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vv19btJOyROvv3RA50FKeTl_w-9LF-doD_SQAUVCq2s)
> 
> you try to use the version: "next-auth": "^5.0.0-beta.4",

i'm using that exact version

**Comment by whcender** [comment]
> > > > > How do you fix this then? <img alt="Screenshot 2024-01-15 at 11 27 11 AM" width="378" src="https://private-user-images.githubusercontent.com/112786129/296854654-62ae25dd-9ec1-42a3-9b66-89c1527ff8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTMyOTQsIm5iZiI6MTcwNTYxMjk5NCwicGF0aCI6Ii8xMTI3ODYxMjkvMjk2ODU0NjU0LTYyYWUyNWRkLTllYzEtNDJhMy05YjY2LTg5YzE1MjdmZjhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMTIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2RiZWRkOGQ0ZmY2YTEzZTk2ZTY0MjhiYzk0ZWEwZGQ2ZmJmOTE1MmNhYjhmMDY1ZjM4NDQxMGFjYTdkMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fptt57aQNiWxvkl76wrvf2JwzDbFTHq1T9WYKnsRI8c">
> > > > 
> > > > 
> > > > +1 i experienced the same below ![image](https://private-user-images.githubusercontent.com/35098691/297887380-82b095c0-cc56-44bb-9f5a-d3cd4e8e86dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MzMzMzMsIm5iZiI6MTcwNTczMzAzMywicGF0aCI6Ii8zNTA5ODY5MS8yOTc4ODczODAtODJiMDk1YzAtY2M1Ni00NGJiLTlmNWEtZDNjZDRlOGU4NmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA2NDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTc5YzEyMDcwMTAyNGJmZmQ4Y2M0MzEyNzQ2OTMzNzY4NmRmZTUyMmI3ZmVkZWU4NjE3MGY5YzNjOTdiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CHu2Lha_a1sTHZD228UkAHKx3lPEZQ3S--ngEMWnqzk)
> > > 
> > > 
> > > I couldn't find a solution. ![Captura de pantalla 2024-01-20 080316](https://private-user-images.githubusercontent.com/63469220/298283472-ba85092d-5256-4be8-9c89-a224b16f1e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODc1OTMsIm5iZiI6MTcwNTc4NzI5MywicGF0aCI6Ii82MzQ2OTIyMC8yOTgyODM0NzItYmE4NTA5MmQtNTI1Ni00YmU4LTljODktYTIyNGIxNmYxZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIxNDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDZlNWFmY2UyOWI1NTRhMWMwMzdkYmNmNzBlMGQ2ZDBmNjc3MDBkNTBmM2M2NjY4ODQzMTZjZGRkNDYxZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vv19btJOyROvv3RA50FKeTl_w-9LF-doD_SQAUVCq2s)
> > 
> > 
> > you try to use the version: "next-auth": "^5.0.0-beta.4",
> 
> i'm using that exact version

same issue, Did you find any solution

**Comment by enricoblanco** [comment]
changing to version 5.0.0-beta.4 actually worked for me

**Comment by jrfullstack** [comment]
![image](https://github.com/nextauthjs/next-auth/assets/96630703/3e23b2fb-4061-4579-85e8-6e4dad5e6e88)

I have the same problem, I tried different versions and couldn't solve it,

Any ideas?

**Comment by koitoror** [comment]
`

TRIED THIS WORKAROUND → 

    async session({ session, trigger, newSession }) {
      const token = newSession?.user?.token || session?.user?.token;
      console.log('JWT token:', token);
  
      if (trigger === 'update' && newSession.user) {
        // Handle/Access the new/session update logic here if needed
        // newSession.user.id, newSession.user.role, etc.
      }

      // return {...session};
      return session;
    },
 `

**Comment by jrfullstack** [comment]
> `
> 
> TRIED THIS WORKAROUND →
> 
> ```
> async session({ session, trigger, newSession }) {
>   const token = newSession?.user?.token || session?.user?.token;
>   console.log('JWT token:', token);
> 
>   if (trigger === 'update' && newSession.user) {
>     // Handle/Access the new/session update logic here if needed
>     // newSession.user.id, newSession.user.role, etc.
>   }
> 
>   // return {...session};
>   return session;
> },
> ```
> 
> `
![image](https://github.com/nextauthjs/next-auth/assets/96630703/5d696503-bd08-42a6-a89e-589eb110652c)
the same problem

**Comment by Banchereau** [comment]
[travistylervii](https://github.com/travistylervii) had found a solution by downgrading to version beta4. Be carefull: you have to delete ^symbol. It worked for me

**Comment by xcodewhisperer** [comment]
[travistylervii](https://github.com/travistylervii) had found a solution by downgrading to beta.4. Be carefull: the ^symbol must deleted. In my case, i did: yarn upgrade next-auth@5.0.0-beta.4.
It worked for me

**Comment by koitoror** [comment]
> > `
> > TRIED THIS WORKAROUND →
> > ```
> > async session({ session, trigger, newSession }) {
> >   const token = newSession?.user?.token || session?.user?.token;
> >   console.log('JWT token:', token);
> > 
> >   if (trigger === 'update' && newSession.user) {
> >     // Handle/Access the new/session update logic here if needed
> >     // newSession.user.id, newSession.user.role, etc.
> >   }
> > 
> >   // return {...session};
> >   return session;
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> > ![image](https://private-user-images.githubusercontent.com/96630703/299613427-5d696503-bd08-42a6-a89e-589eb110652c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMTY2ODUsIm5iZiI6MTcwNjIxNjM4NSwicGF0aCI6Ii85NjYzMDcwMy8yOTk2MTM0MjctNWQ2OTY1MDMtYmQwOC00MmE2LWE4OWUtNTg5ZWIxMTA2NTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDIwNTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMmIyYWNjMWVmNjdlYThmNjZjMTg3YTRiMmY5ODNjMjFmNjMyNmZmMjQ5ZDFkNzIwNjc4ZThiNDM0MTk2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3VhrZ9UvSIZGAp65aVpHp69ffS9vUcr2mqPngdW-CLs)
> > the same problem

it depends on the shape of your user type if extended to add/carry token field

**Comment by jrfullstack** [comment]
> [travistylervii](https://github.com/travistylervii) had found a solution by downgrading to beta.4. Be carefull: the ^symbol must deleted. In my case, i did: yarn upgrade next-auth@5.0.0-beta.4. (issue [9633](https://github.com/nextauthjs/next-auth/issues/9633)) It worked for me.

thanks this worked for me
in package.json
"next-auth": "5.0.0-beta.4",

**Comment by jrfullstack** [comment]
thanks this worked for me,

package.json
"next-auth": "5.0.0-beta.4",

auth.config.ts
trustHost: true, // for build

**Comment by koitoror** [comment]
`"next-auth": "^5.0.0-beta.4"`, install resolves to the latest undocumented unstable `5.0.0-beta.5` necessitating the workaround

**Comment by jarrodmedrano** [comment]
I am using PostgresAdapter, I got this far, but only getting an error on Adapter User
`declare module 'next-auth' {
  export interface User extends DefaultUser {
    id: string
    isAdmin: boolean
    role: string
  }

  export interface Session {
    user: User
  }

  export interface JWT {
    user: {
      id: string
      role: string
    }
  }
}

declare module '@auth/core/adapters' {
  export interface AdapterUser extends DefaultAdapterUser {
    isAdmin: boolean
    id: string
    role: string
  }
}`

![Screenshot 2024-02-03 at 9 44 51 AM](https://github.com/nextauthjs/next-auth/assets/1929136/7041e7b7-dbfb-4c7c-9396-e6ac4a23a44c)

**Comment by luislealdev** [comment]
> changing to version 5.0.0-beta.4 actually worked for me

Thank you so much!!

**Comment by gbo3000** [comment]
try
1.Extend the User Type in NextAuth: You need to extend the default Session and User types in NextAuth to include the id property. This can be done by creating a next-auth.d.ts file to extend the type definitions.

2.Create or Modify next-auth.d.ts: Create a next-auth.d.ts file in your project, typically inside the types or src folder.
![image](https://github.com/user-attachments/assets/fcb513db-7d1f-4a3b-afe5-55a081c1cb85)

3.Update Your NextAuth Options: If you’re using a custom callback, ensure that you include the id when returning the user object.
![image](https://github.com/user-attachments/assets/6c1ae428-e21b-4aa6-bc23-4e34cf3195f6)

answer from gpt. worked for me!

**Comment by sdilonedev** [comment]
Same issue here, i'm using `5.0.0-beta.22` with next-auth/jwt
![image](https://github.com/user-attachments/assets/f5faa3ac-49d3-4b3b-9e65-46876652b6aa)
![image](https://github.com/user-attachments/assets/d41957f7-8375-4fc6-8ad5-c4dc72fb01f3)

**Comment by skeddles** [comment]
Same issue, in both the current and beta.

```
import NextAuth from "next-auth"
import GoogleProvider from "next-auth/providers/google"
import PostgresAdapter from "@auth/pg-adapter"
import { Pool } from "pg"

type SessionProps = {
	session: {
		user: {
			id: string;
			name?: string;
			email: string;
			image?: string;
		};
	};
	user: {
		id: string;
	};
};
  
const pool = new Pool({
	host: process.env.POSTGRES_HOST,
	user: process.env.POSTGRES_USER,
	password: process.env.POSTGRES_PASSWORD,
	database: process.env.POSTGRES_DATABASE,
	max: 20,
	idleTimeoutMillis: 30000,
	connectionTimeoutMillis: 2000,
	ssl: {rejectUnauthorized: false} // This is for local development only
});

const googleProvider = GoogleProvider({
	clientId: process.env.GOOGLE_CLIENT_ID || "",
	clientSecret: process.env.GOOGLE_CLIENT_SECRET || ""
});

const callbacks = {
	session: ({ session, user }: SessionProps) => {
		session.user.id = user.id;
		return session;
	}
}

export const { auth, handlers, signIn, signOut } = NextAuth({
	adapter: PostgresAdapter(pool),
	providers: [googleProvider],
	callbacks: callbacks
}); 

```

```
./auth.ts:46:2
Type error: Type '{ session: ({ session, user }: SessionProps) => { user: { id: string; name?: string; email: string; image?: string; }; }; }' is not assignable to type '{ signIn?: ((params: { user: AdapterUser | User; account: 
Account | null; profile?: Profile | undefined; email?: { verificationRequest?: boolean | undefined; } | undefined; credentials?: Record<...> | undefined; }) => Awaitable<...>) | undefined; redirect?: ((params: { ...; }) => Awaitable<...>) | undefined; session...'.
  Type '{ session: ({ session, user }: SessionProps) => { user: { id: string; name?: string; email: string; image?: string; }; }; }' is not assignable to type '{ signIn?: ((params: { user: AdapterUser | User; account: Account | 
null; profile?: Profile | undefined; email?: { verificationRequest?: boolean | undefined; } | undefined; credentials?: Record<...> | undefined; }) => Awaitable<...>) | undefined; redirect?: ((params: { ...; }) => Awaitable<...>) | undefined; session...'.
    The types returned by 'session(...)' are incompatible between these types.
      Type '{ user: { id: string; name?: string | undefined; email: string; image?: string | undefined; }; }' is not assignable to type 'Awaitable<Session | DefaultSession>'.
        Property 'expires' is missing in type '{ user: { id: string; name?: string | undefined; email: string; image?: string | undefined; }; }' but required in type 'DefaultSession'.

  44 |  adapter: PostgresAdapter(pool),
  45 |  providers: [googleProvider],
> 46 |  callbacks: callbacks
     |  ^
  47 | }); 
  48 |
  49 |
  ```
  
  ```
  ./app/account/page.tsx:9:17
Type error: Type 'import("Y:/Projects/Websites/votelo/node_modules/@auth/core/types").Session' is not assignable to type 'Session'.
  Types of property 'user' are incompatible.
    Type 'User | undefined' is not assignable to type '{ name?: string | undefined; id?: string | undefined; } | undefined'.
      Type 'User' is not assignable to type '{ name?: string | undefined; id?: string | undefined; }'.
        Types of property 'name' are incompatible.
          Type 'string | null | undefined' is not assignable to type 'string | undefined'.
            Type 'null' is not assignable to type 'string | undefined'.
            ```
            
 This is very confusing and complicated, I had hoped nextauth would make things easier
