### ISSUE TITLE
Custom pages do not work with App router. 

### ISSUE THREAD

**Issue by DrillableBit** [nextauthjs/next-auth#8242]
### Environment

    "next": "13.4.12",
    "next-auth": "^4.22.3",
    "react": "18.2.0",
    Chrome @ latest
    Windows 11 @ latest

### Reproduction URL

https://github.com/DrillableBit/next-debug

### Describe the issue

Comment out "pages" in authOptions inside [...nextauth] and everything should work as expected. 
User can click "API Auth" in the navbar and login, and generate a session object. 

Following the documentation from "https://next-auth.js.org/configuration/pages"
"To add a custom login page, you can use the pages option:"
"You can also use the signIn() function which will handle obtaining the CSRF token for you:"

After adding the pages option, and using the signIn() function - as in the github repo, I get the following error when attempting to log in: 

[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Failed to fetch {error: {…}, url: '/api/auth/csrf', message: 'Failed to fetch'}

Following the link suggests adding the NEXTAUTH_URL env variable, this has been done. 

I have tested various different providers, and wonder if this is a bug with the new app router?

I have seen several posts asking for a demo of custom pages with app router, but there are none available online. 
It would be beneficial for the community to have at least one working example. 

### How to reproduce

npm i, 
npm run dev
press "Custom Auth" in the navbar
login
view browser console log with "preserve log" enabled 

### Expected behavior

[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Failed to fetch {error: {…}, url: '/api/auth/csrf', message: 'Failed to fetch'}

**Comment by mprync** [comment]
If you want to login using your own login page (not the next-auth provided one), then you need to uncomment this line in your code:

https://github.com/DrillableBit/next-debug/blob/3821e1f0c5baceb3892669e39804985d0ac80ce0/src/app/auth/signin/page.tsx#L18

redirect:false is required and you also should remove the "credentials" fields for username and password. Just leave an empty "credentials" object.

```js
CredentialsProvider({
    name: 'Credentials',
    credentials: {
      /* Empty credentials since we want to use a custom 
      login screen and not have it generated for us */
    },
    async authorize(credentials) { ... }
  }
});
```

Then call sign in like this:

```js
return await signIn('credentials', {
      username: data.phoneNumber,
      password: data.password,
      redirect: false,
    })
```

Then that should log you in and you should have a session cookie.

**Comment by balazsorban44** [comment]
@mprync that is incorrect information.

App Router has been supported since last year November, and we added Route Handler support back in April, Middleware was already supported even longer, so you can create an entire app using only the APP Router + NextAuth.js

See the docs:

https://next-auth.js.org/configuration/nextjs#getserversession

https://next-auth.js.org/configuration/nextjs#middleware

https://next-auth.js.org/configuration/initialization#route-handlers-app

If something is missing, let us know. 

Admittedly, the official example is not converted yet, ut we plan to do so, as part of #7443


That said @DrillableBit, setting NEXTAUTH_URL should not be needed in the default case, can you try to remove it and see what happens? Do you see any other errors in the terminal that could help debugging your issue?

**Comment by mprync** [comment]
Sorry, I wasn't being specific enough.

It's not stable "in my opinion".

1. The docs aren't fully covered, there are many different versions of it and some important things aren't even in the docs.
2. The above issue is reproducible
3. Getting a failed login through "signIn" client side function ALWAYS returns success 200, which makes no sense.
4. Setting up a custom login screen is not documented, or at least I couldn't find it.
5. Setting up a global session object (passing through the provider) is not documented for app router. It's definitely needed because getting the session through useSession causes a delay if you don't.
6. getServerSession is marked as "EXPERIMENTAL API", so it's not stable?

I could go on but these things make it not stable for large applications. I've only used it for credentials and only god knows what issues lie in the custom providers.

Don't get me wrong, I really like the library and potentially moving it to the edge!

I will continue to use it regardless since I've invested into it and I can't wait for v5!

**Comment by DrillableBit** [comment]
@balazsorban44 
-commenting out NEXTAUTH_URL causes no difference. However I do get an 
![Screenshot 2023-08-07 005045](https://github.com/nextauthjs/next-auth/assets/94070914/e25650ef-3ea0-4b8d-81f0-2994e15e0e35)


-Ocassionally I get the following error instead: 
![Screenshot 2023-08-07 004910](https://github.com/nextauthjs/next-auth/assets/94070914/8d9737bb-59b0-45e9-a32f-2f3e5d5c45a1)

Visiting the link gives me a csrf token like : {"csrfToken":"aecbaabfa0c30dca6c219536154250b281128ee2522cf6543ba0c200f45a2efa"}

Checking the request in consol shows that it stalls, and is then cancelled: 
![Uploading Screenshot 2023-08-07 004349.png…]()

**Comment by balazsorban44** [comment]
Thanks! The second screenshot is broken.

**Comment by DrillableBit** [comment]
Should be fixed now

**Comment by balazsorban44** [comment]
@mprync Appreciate the direct/addressable feedback, more than discouraging claims. 🙏

1. Please let us know what is unclear/missing by opening an issue, or better yet, a PR that we can review!
2. All software (even stable) has bugs, that's why this issue tracker is here. I'm already looking into it.
3. API design is debatable, but there is historical context here. The reason you currently get a 200 is because the actual signin request is successful, but the `error` property will tell you what the issue was/is. Haven't seen enough complaints about this to have a closer look.
4. https://next-auth.js.org/configuration/pages#examples
5. The App Router's innovation is RSC (server components), which will ultimately make "global providers" unnecessary, at least for authentication. You are better off with only using `getServerSession` and occasionally passing down the session to client components instead, where actually needed. Again, this is already full possible, but v5 will improve the DX around this dramatic.
6. We recently dropped the experimental messaging, as it's been stable for a very long time and has been our main recommendation. Please upgrade.

Hope this helps to clarify things a bit! Thanks for using NextAuth.js! 💚

**Comment by balazsorban44** [comment]
So I could not directly reproduce the CSRF issue, but I found some problems in the implementation. You were importing `Layout` into the page, which is unnecessary, since Next.js already wraps the `page.tsx` for you, with `layout.tsx`. This caused an issue since you defined `metadata` in layout, which is a Server Component, while you marked `page.tsx` with `use client`. You should have seen an error and a link to the Next.js docs about this:

![image](https://github.com/nextauthjs/next-auth/assets/18369201/65eabb98-f560-45ab-8beb-7a3312b7996b)


In any case, here is a simplified version of what you were trying to achieve, which works as expected: 
```js
"use client";
import React, { useState } from "react";
import Navbar from "../../../components/Navbar";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";

export default function SignIn() {
  const [error, setError] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();
  return (
    <>
      <Navbar />
      <div className="container mx-auto p-4">
        <h1 className="text-4xl font-bold text-center">Login</h1>
        <form
          className="mt-4 mx-auto max-w-sm"
          onSubmit={async (e) => {
            try {
              e.preventDefault();
              const response = await signIn("credentials", {
                username: username,
                password: password,
                redirect: false,
                callbackUrl: window.location.origin,
              });
              if (response?.error) throw new Error(response.error);
              router.push(response?.url ?? "/");
            } catch (error) {
              setError(
                e instanceof Error ? e.message : "An unknown error occurred."
              );
            }
          }}
        >
          <div className="mb-4">
            <input
              className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:border-blue-300"
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>
          <div className="mb-4">
            <input
              className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:border-blue-300"
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <button
            className="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
            type="submit"
          >
            Login
          </button>
          {error}
        </form>
      </div>
    </>
  );
}
```

**Comment by DrillableBit** [comment]
Aha! The form is reloading before it has a chance to send the data to the next-auth backend. Adding e.preventDefault() fixes it. Thanks a million.

**Comment by rahul-reveation** [comment]
> 6. We recently dropped the experimental messaging, as it's been stable for a very long time and has been our main recommendation. Please upgrade.

@balazsorban44 I still see experimental messaging on auth.js document unless I am referencing wrong link 

![image](https://github.com/nextauthjs/next-auth/assets/73868123/f39726c5-8ec7-40f5-962e-9fb9f08c959d)

**Comment by balazsorban44** [comment]
Auth.js is a set of libraries, which are still under active development.

NextAuth.js (v4) - what's being discussed here - is stable though and has been with all of its features as mentioned.
